### ISSUE TITLE
BART- Get cross attention of all layers in the inference 

### ISSUE THREAD

**Issue by shamanez** [facebookresearch/fairseq#2257]
## 🚀 Feature Request
Write now, BART implementation only outputs the cross attention of the last decoder layer. It would be nice to get all the attention weights during the inference. 

### Motivation

This will allow us to explore layer-wise attention for the task of abstraction summarization.

### Pitch

It would be nice to integrate this to the **def generate** function in the **hub_interface.py script**.

**Comment by NadjaHergerTR** [comment]
Hi there. I'm running into the same issue. Would you be able to share any updates in terms of extracting attention from other BART layers?

**Comment by shamanez** [comment]
@NadjaHergerTR  Any update on this?

**Comment by NadjaHergerTR** [comment]
> @NadjaHergerTR Any update on this?

Hi @shamanez . No updates from my side unfortunately.

**Comment by shamanez** [comment]
I tried to get them out. But it is super hacky. Basically you need to go to transformer.py and take attention layers weights out from the forward function in the Decoder.

**Comment by HeegonJin** [comment]
bump
