### ISSUE TITLE
How to load the checkpoint for s2t_transformer_s trained with CoVoST for predictions

### ISSUE THREAD

**Issue by makermotion** [facebookresearch/fairseq#3069]
#### How to load the checkpoint for s2t_transformer_s trained on CoVoST for predictions

I have trained an ASR for Speech to Text for Turkish with CoVoST dataset. I want to load my best checkpoint and do some predictions. But couldn't figure out how to do that. I tried the way which explained for RoBERTa  on issue #1421 . The code below, returned the error "ModuleAttributeError: 'GeneratorHubInterface' object has no attribute 'predict'"
I saw @myleott answered on issue #1421, maybe also can help with this?

#### Code

``` 
from fairseq.models.speech_to_text import S2TTransformerModel
model = S2TTransformerModel.from_pretrained('path/to/checkpoint', checkpoint_file='checkpoint_best.pt')
model.eval()
model.predict(args)
```

#### What's your environment?

 - fairseq Version (e.g., 1.0 or master): 0.10.0
 - PyTorch Version (e.g., 1.0): 1.7.0
 - OS (e.g., Linux): Ubuntu 20.04
 - How you installed fairseq (`pip`, source):
 - Build command you used (if compiling from source):
 - Python version: 3.8.5
 - CUDA/cuDNN version: 10.1
 - GPU models and configuration: RTX 2070 Super (single)
 - Any other relevant information:

**Comment by cromz22** [comment]
Hi, did you try `fairseq-generate` command described [here](https://github.com/pytorch/fairseq/tree/master/examples/speech_to_text#example-3-st-on-covost)?
I didn't try it in Turkish, but I think it should work.
You may also need to replace [these lines](https://github.com/pytorch/fairseq/blob/master/fairseq_cli/generate.py#L173-L174) by following (see https://github.com/pytorch/fairseq/issues/2971 for more details):

```
tokenizer = task.build_tokenizer(cfg)
bpe = task.build_bpe(cfg)
```

**Comment by makermotion** [comment]
hey, thanks for the answer @cromz22. but my intention is  not to use cli. I'd like to make it a script. Looking for a clean way. Otherwise I can go hacky but honestly don't want to.

**Comment by makermotion** [comment]
hey @kahne , anything new about this?
