### ISSUE TITLE
Wav2Vec 2.0 pretraining limited by CPU even on large machine

### ISSUE THREAD

**Issue by marma** [facebookresearch/fairseq#3342]
I'm running wav2vec 2.0 pretraining on a DGX A100  and I seem to be CPU-limited which is a bit surprising given the amount of CPU resources the machine has. The GPUSs seem to be working at barely 50%. When I lower the GPU count to four I get basically the same updates / time unit but with higher GPU load per GPU.

I have tried running with and without `+optimization.update_freq='[x]'` parameter with somewhat similar result. The CPU load is lower without it, bit GPU utilization is about the same.

Any thoughts?

**Setup**:
NVIDIA DGX A100
8 x A100 GPU
2 x 64 core / 128 thread CPU
1TB RAM
Ubuntu 20.04
Code runs inside NVIDIA NGC container

**Comment by Slyne** [comment]
same issue here. Can anyone share the GPU utilization ?

**Comment by lubossmidl** [comment]
I have the same problem...

**Comment by lubossmidl** [comment]
the training process seems to be over-optimized on large machine ...
try to use parameter OMP_NUM_THREADS=1
like
OMP_NUM_THREADS=1 fairseq-train ...

(8 x A100 GPU / 128 thread CPU: GPU utilization approx. 97-100% and CPU 8% instead of GPU 30% and 100% CPU)

**Comment by marma** [comment]
Thank you @lubossmidl! I did not see this as I had moved on to other things. Closing issue.

Funny story: we debugged a similar issue today and found this exact solution. I remembered this issue and went back to look at it. If only I had read you answer two years ago we would have saved a few hours :)
