### ISSUE TITLE
cant reproduce mustc en-de ASR and ST

### ISSUE THREAD

**Issue by holyma** [facebookresearch/fairseq#3897]
I have run this example( mustc en-de ASR and ST) with 1 GPU and set `--update-freq 8`. All instructions are the same as [this](https://github.com/pytorch/fairseq/blob/master/examples/speech_to_text/docs/mustc_example.md). But I get some terrible results. It is normal? Does someone have the same things? Anyone help me with some things. 

Here are some of my results.

```
# 1.ASR in mustc en-de
# train log
| train | epoch 017 | loss 5.83 | nll_loss 4.735 | total 12447.3 | n_correct 4712.16 | ppl 26.62 | accuracy 37.857 | wps 4720.7 | ups 0.38 | wpb 12447.3 | bsz 453.9 | num_updates 8313 | lr 0.0008313 | gnorm 0.503 | clip 0 | train_wall 1217 | gb_free 13.2 | wall 7199
| train | epoch 110 | loss 4.691 | nll_loss 3.373 | total 12454.6 | n_correct 6415.92 | ppl 10.36 | accuracy 51.514 | wps 4538.9 | ups 0.36 | wpb 12454.6 | bsz 455.1 | num_updates 53791 | lr 0.000431167 | gnorm 0.414 | clip 0 | train_wall 1229 | gb_free 13.3 | wall 12006
| train | epoch 205 | loss 4.503 | nll_loss 3.153 | total 12457.3 | n_correct 6736.07 | ppl 8.9 | accuracy 54.073 | wps 4620.8 | ups 0.37 | wpb 12457.3 | bsz 454.9 | num_updates 100000 | lr 0.000316228 | gnorm 0.38 | clip 0 | train_wall 607 | gb_free 13.4 | wall 54929

# generate log
epoch 12: Generate tst-COMMON_asr with beam=5: WER: 118.71
epoch 102: Generate dev_asr with beam=5: WER: 85.50
epoch 127: Generate dev_asr with beam=5: WER: 81.73
epoch 161: Generate dev_asr with beam=5: WER: 79.54
```

```
# 2.ST in mustc en-de with ASR pretrained
# train log
| train | epoch 020 | loss 6.389 | nll_loss 5.274 | total 12009.8 | n_correct 3959.4 | ppl 38.7 | accuracy 32.968 | wps 4981.4 | ups 0.41 | wpb 12009.8 | bsz 454.4 | num_updates 9776 | lr 0.0019552 | gnorm 0.238 | clip 0 | loss_scale 128 | train_wall 817 | gb_free 13.3 | wall 24843
| train | epoch 071 | loss 5.771 | nll_loss 4.529 | total 5440.78 | n_correct 2138.73 | ppl 23.08 | accuracy 39.309 | wps 4220.2 | ups 0.78 | wpb 5440.8 | bsz 206.6 | num_updates 64434 | lr 0.000787902 | gnorm 0.325 | clip 0 | loss_scale 64 | train_wall 1296 | gb_free 13.4 | wall 67821

# generate log
epoch 20: Generate tst-COMMON_st with beam=5: BLEU = 1.10 18.5/2.1/0.4/0.1 (BP = 1.000 ratio = 1.197 hyp_len = 62037 ref_len = 51829)
epoch 71: Generate tst-COMMON_st with beam=5: BLEU = 1.56 18.5/2.5/0.6/0.2 (BP = 1.000 ratio = 1.224 hyp_len = 63461 ref_len = 51829)
```

**Comment by holyma** [comment]
In the training process, there are frequent warnings. Has this impacted the train results?
`| WARNING | fairseq.trainer | OOM: Ran out of memory with exception: CUDA out of memory.`

**Comment by holyma** [comment]
I have download the pre-trained [model](https://github.com/pytorch/fairseq/blob/fcca32258c/examples/speech_to_text/docs/mustc_example.md) (en-de ASR/ST). and check all my preprocessed data(include dev, tst-common, tst-HE and part of train), it runs very well(show that the dataset is correct).

**Comment by dearchill** [comment]
I ran my en-zh ST training using Covost2 corpus and tested on the test split, and i couldn't reproduce the result **(BLEU 25.4)** in the [paper](https://arxiv.org/pdf/2007.10310.pdf) either. Here's my result:
**Generate test_st_en_zh-CN with beam=5: BLEU = 2.34 17.5/4.9/0.9/0.5 (BP = 0.911 ratio = 0.914 hyp_len = 34016 ref_len = 37198)**

And Here are some translation results:
T-4139  他父亲的去世使他无法继续完成学业。
H-4139  -0.6948603391647339     ▁他 父亲的 去世 使他 无法 继续 他的 学术 。
D-4139  -0.6948603391647339     他父亲的去世使他无法继续他的学术。
P-4139  -3.1920 -0.2355 -1.0795 -0.1963 -0.0824 -0.0328 -0.2243 -0.4684 -1.2981 -0.1392
T-6166  芬兰人和其他人称该地区为 Copper 岛。
H-6166  -0.6394014954566956     ▁ 芬兰 人和 其他人 称 该地区 为 铜 岛 。
D-6166  -0.6394014954566956     芬兰人和其他人称该地区为铜岛。
P-6166  -1.1097 -1.2543 -1.8965 -1.1755 -0.3279 -0.1899 -0.1034 -0.3750 -0.2390 -0.2108 -0.1513
T-10147 俱乐部的吉祥物改变了很多次。
H-10147 -1.2383558750152588     ▁ 俱乐部的 吉祥物 已经 多次 更改 。
D-10147 -1.2383558750152588     俱乐部的吉祥物已经多次更改。
P-10147 -2.8543 -0.7875 -2.2960 -1.1378 -1.3495 -1.0557 -0.2889 -0.1371
T-6867  他喜欢在阳台上看杂志和粉丝来信。
H-6867  -1.4278584718704224     ▁他 经常在 狗 的 注视 下 进行 海军 、 救 助 人和 法 人 。
D-6867  -1.4278584718704224     他经常在狗的注视下进行海军、救助人和法人。
P-6867  -1.0173 -2.6370 -2.1187 -3.0456 -2.2221 -0.0492 -1.5831 -1.1248 -1.3173 -3.2947 -0.5004 -1.1187 -1.7990 -0.7445 -0.1418 -0.1317
T-7239  气体逸出时,岩浆的结晶温度升高。
H-7239  -1.474063754081726      ▁ 岩 心 化 对 磁 铁 的 缩 微 加剧 了 。
D-7239  -1.474063754081726      岩心化对磁铁的缩微加剧了。
P-7239  -0.7999 -3.3521 -2.6146 -0.3363 -0.8846 -0.8297 -0.8990 -0.0936 -2.5773 -2.8949 -1.1658 -1.0305 -3.0174 -0.1412
T-7700  甜玉米烤熟更好吃。
H-7700  -1.053934097290039      ▁ 甜 菜 根 是我 最喜欢的 糖果 棒
D-7700  -1.053934097290039      甜菜根是我最喜欢的糖果棒
P-7700  -0.6305 -0.1082 -0.8605 -0.0312 -0.3018 -5.0504 -1.3257 -0.8581 -0.3189

I also tested with three sentencepiece types:
**char + 1k vocab-size
unigram + 10k vocab-size
bpe + 20k vocab-size just as the paper says**
 And all of them can't reproduce the result. Can someoone told me how to do?

My train command is as followed (I used the pretrained en asr model):
`fairseq-train /data/juicefs_translation/11119758/fairseq_nmt/zh_en_0910_st/covost/en --config-yaml config_st_en_zh-CN.yaml --train-subset train_st_en_zh-CN --valid-subset dev_st_en_zh-CN --save-dir ./st_models_bpe --num-workers 10 --max-tokens 120000 --max-update 40000 --task speech_to_text --criterion label_smoothed_cross_entropy --label-smoothing 0.1 --report-accuracy --arch s2t_transformer_s --encoder-freezing-updates 1000 --optimizer adam --lr 2e-3 --lr-scheduler inverse_sqrt --warmup-updates 10000 --clip-norm 10.0 --seed 1 --update-freq 8 --load-pretrained-encoder-from ./covost2_en_asr_transformer_s.pt --fp16`

and my test command:
`fairseq-generate . --config-yaml config_st_en_zh-CN.yaml --gen-subset test_st_en_zh-CN --task speech_to_text --path ./st_models_bpe/model_avg.pt --max-tokens 200000 --beam 5 --scoring sacrebleu --skip-invalid-size-inputs-valid-test`

**Comment by cordercorder** [comment]
Since there is not space between words in Chinese and Japanese. When the target language is Chinese or Japanese, the BLEU is calculated based on character-level (please refer to section 4.1 of [paper](https://arxiv.org/pdf/2007.10310.pdf) ). Trying to set --sacrebleu-tokenizer to zh or ja-mecab.

**Comment by holyma** [comment]
> Since there is not space between words in Chinese and Japanese. When the target language is Chinese or Japanese, the BLEU is calculated based on character-level (please refer to section 4.1 of [paper](https://arxiv.org/pdf/2007.10310.pdf) ). Trying to set --sacrebleu-tokenizer to zh or ja-mecab.

when I train the S2T model, always show 'CUDA OOM' warning. So I try to reduce `max-tokens` , at the same time, Do I need to change some other params (such as `warmup-updates` and `max-update`)

**Comment by dearchill** [comment]
> Since there is not space between words in Chinese and Japanese. When the target language is Chinese or Japanese, the BLEU is calculated based on character-level (please refer to section 4.1 of [paper](https://arxiv.org/pdf/2007.10310.pdf) ). Trying to set --sacrebleu-tokenizer to zh or ja-mecab.

Thanks for your reply. I used the char-level evaluation, and the BLEU is around 20. I'll train more times to figure out where's the gap.

**Comment by yuntang** [comment]
> > Since there is not space between words in Chinese and Japanese. When the target language is Chinese or Japanese, the BLEU is calculated based on character-level (please refer to section 4.1 of [paper](https://arxiv.org/pdf/2007.10310.pdf) ). Trying to set --sacrebleu-tokenizer to zh or ja-mecab.
> 
> when I train the S2T model, always show 'CUDA OOM' warning. So I try to reduce `max-tokens` , at the same time, Do I need to change some other params (such as `warmup-updates` and `max-update`)

It might hurt the performance if we reduce the max-tokens, what's the number do you choose? 
cc @kahne

**Comment by holyma** [comment]
I have reduced max-token（40000->20000） and added update-freq（8->16） to compensate（according to #3422），and I get similar results as above. @yuntang

**Comment by yuntang** [comment]
They are not equivalent. Many long utterances will be dropped due to smaller max-token value. Please check how much data has been dropped.

**Comment by holyma** [comment]
> They are not equivalent. Many long utterances will be dropped due to smaller max-token value. Please check how much data has been dropped.

when show `CUDA OOM`，I reduce the max-token( how many is suitable )，and do I need to do anything else(such as ,change other params)？

**Comment by yuntang** [comment]
I'd suggest to try small model configuration first.

**Comment by holyma** [comment]
Small model config already used, but still OOM. I have re-preprocess the data and trained with pytorch=1.9 and torchabudio=0.9.1 ignore  OOM, it is run well as the published result. Thanks @yuntang

**Comment by holyma** [comment]
Already solved. Maybe because I ignored the WARNING of 'sox_io' in torchaudio==0.7. After upgrading, it works well.
