### ISSUE TITLE
urllib.error.HTTPError: HTTP Error 404: Not Found

### ISSUE THREAD

**Issue by yrf1** [facebookresearch/fairseq#3902]
#### What is your question?
`torch.hub.load('pytorch/fairseq', 'roberta.large')` leads to url not found error.

#### What have you tried?
I also tried to look at the link https://github.com/pytorch/fairseq/archive/master.zip but the link is broken?

#### What's your environment?
- python 3.8
- torch 1.7.1
- Ubuntu 18.04

**Comment by GeekDream-x** [comment]
Bro, you could try to add ":main" at the end of the first parameter, this helped me.
Like this: `xlmr = torch.hub.load('pytorch/fairseq:main', 'xlmr.large')`
