### ISSUE TITLE
How to restore the checkpoint in wav2vec (fairseq-hydra-train))

### ISSUE THREAD

**Issue by r03943158** [facebookresearch/fairseq#3927]
### Before asking:
1. search the issues.
2. search the docs.

#### What is your question?

Hi, I want to restore the checkpoint to continue the training processing. 
However, I can't find the parser (--restore_file) in the fairseq-hydra-train. It only can be found in the fairseq-train.
How to restore the checkpoint on wav2vec (fairseq-hydra-train))?

Thank you.

#### What's your environment?

 - fairseq Version (e.g., 1.0 or main):
 - PyTorch Version (e.g., 1.0) 1.9
 - OS (e.g., Linux): Linux
 - How you installed fairseq (`pip`, source): source
 - Build command you used (if compiling from source):
 - Python version: 3.7
 - CUDA/cuDNN version: 11.0
 - GPU models and configuration: Nviaia-V100
 - Any other relevant information:

**Comment by ahazeemi** [comment]
@r03943158 We can use `checkpoint.restore_file` for it:

```
fairseq-hydra-train \
    task.data=/path/to/data \
    checkpoint.restore_file=/path/to/checkpoint
    --config-dir /path/to/fairseq-py/examples/wav2vec/config/pretraining \
    --config-name wav2vec2_large_librivox
```

**Comment by r03943158** [comment]
@ahazeemi Thank you! It seems the script works fine.
