### ISSUE TITLE
Training time about Wav2vec2 pretrained on librispeech

### ISSUE THREAD

**Issue by r03943158** [facebookresearch/fairseq#3928]
### Before asking:
1. search the issues.
2. search the docs.

#### What is your question?

Hi, I am using 8x Nvidia-V100 to train the wav2vec2 (base-model) on librispeech (100 hours).
I set distributed_training.distributed_world_size=8 and the optimization.update_freq='[8]'.
It takes 20 minutes for one epoch (73 updated), and the 400000 updated need two mouths. So it seems much slower than the number in the paper (1.6 days with 64 v100 on 900 hours). Can anyone provide the experience on the training time?
Thank you! 

#### What have you tried?

I tried to move the dataset to share memory to eliminate the I/O cost, but the time is still the same.

#### What's your environment?

 - fairseq Version (e.g., 1.0 or main): 1.0.0a0+f2146bd
 - PyTorch Version (e.g., 1.0) 1.9
 - OS (e.g., Linux): Linux
 - How you installed fairseq (`pip`, source): source
 - Build command you used (if compiling from source):
 - Python version: 3.7
 - CUDA/cuDNN version: 11.0
 - GPU models and configuration: 8x Nvidia-v100
 - Any other relevant information: apex 0.1

**Comment by thechuong98** [comment]
Hi, I'm facing the same issue? Have you found a way to fix it yet?

**Comment by ductho9799** [comment]
Hi, I'm facing the same issue? Have you found a way to fix it yet?
