### ISSUE TITLE
Iteration amount of pre-training wav2vec 2.0 base

### ISSUE THREAD

**Issue by yuanfeng-yl** [facebookresearch/fairseq#3949]
#### What is your question?
I want to know the how many epoches did you spend fully pre-training the wav2vec 2.0 base model on full 960 hours' LibriSpeech dataset.
I know that you set the max_update as 400000 for stop condition. But after some trial pre-training, I think it is very hard to reach 400000 epoches in 1.6 days with 64 100v GPUs.

#### What have you tried?
I have did some trial pre-training with wav2vec 2.0 base model on full 960 hours' Librispeech. After estimation, I think that probably your pre-training do not reach the max_update.

#### What's your environment?

 - fairseq Version (e.g., 1.0 or main): 1.0
 - PyTorch Version (e.g., 1.0): 1.8.1
 - OS (e.g., Linux): Linux
 - Python version: 3.8.10
 - CUDA/cuDNN version: 10.2
 - GPU models and configuration: 4 v100 GPUs

**Comment by r03943158** [comment]
Hi, can I ask the time cost in one epoch? 
I use 100 hours's LibriSpeech with 8 v100. It cost 20 minutes for 73 updates.
