### ISSUE TITLE
Link to pre-trained VCTK tts_transformer model is broken

### ISSUE THREAD

**Issue by slegroux** [facebookresearch/fairseq#3952]
## 🐛 Bug

The link for downloading the vctk transformer model is broken:

https://dl.fbaipublicfiles.com/fairseq/s2/vctk_transformer_phn.tar

### To Reproduce

Go to https://github.com/pytorch/fairseq/blob/main/examples/speech_synthesis/docs/vctk_example.md
Click on the download link for tts_transformer
See 404

#### Code sample
N/A

### Expected behavior

Browser should start downloading pretrained model.

### Environment
N/A

### Additional context
N/A

**Comment by kahne** [comment]
Thanks for the bug report! We've re-uploaded the file.

**Comment by slegroux** [comment]
Great! thanks!
