### ISSUE TITLE
Speech Synthesis: LJ Speech example. (TTS) 

### ISSUE THREAD

**Issue by agupta54** [facebookresearch/fairseq#3969]
In LJSpeech example, pre-computed forced-alignment from Montreal Forced Aligner and pseudo text units from HuBERT are given. Can more information be given as to how these units can be made from other ASR models like wav2vec 2.0 for languages which are different from English?

**Comment by kahne** [comment]
For getting forced-alignment info (in .TextGrid files) from MFA, please refer to its documentation: https://montreal-forced-aligner.readthedocs.io/en/latest . MFA has pre-trained models for non-English languages and you could also train FA models using your own data.

For extracting pseudo-text units from HuBERT, here is the documentation: https://github.com/pytorch/fairseq/tree/main/examples/hubert
