### ISSUE TITLE
error when install megatron

### ISSUE THREAD

**Issue by trangtv57** [facebookresearch/fairseq#3971]
## 🐛 Bug
hi,
I want to training language model with transformer_lm by multi GPU, and program show error 
`ModuleNotFoundError: No module named 'fairseq.model_parallel.megatron.mpu'`
after that error show suggest install megatron:
```
Please install the megatron submodule:
  git submodule update --init fairseq/model_parallel/megatron
```
but when i am running this command, another error occurr:
```
fatal: reference is not a tree: adb23324c222aad0aad89308e70302d996a5eaeb
Unable to checkout 'adb23324c222aad0aad89308e70302d996a5eaeb' in submodule path 'fairseq/model_parallel/megatron'
```
I clone and using the lastest version of fairseq. How can i fix this problem, thankyou

**Comment by ayushnoori** [comment]
Following-up here; I received the same error when attempting to install [Graphormer ](https://github.com/microsoft/Graphormer) (i.e., `git clone --recursive https://github.com/microsoft/Graphormer.git` at 2e48f3fb52d25d505d0950f74a6016c5f9967c13).
```
fatal: reference is not a tree: adb23324c222aad0aad89308e70302d996a5eaeb
Unable to checkout 'adb23324c222aad0aad89308e70302d996a5eaeb' in submodule path 'fairseq/fairseq/model_parallel/megatron'
Failed to recurse into submodule path 'fairseq'
```

**Comment by IanMGriff** [comment]
I too am running into this issue when attempting to install fairseq as instructed in the current README

**Comment by IanMGriff** [comment]
@trangtv57  did you find a solution to this?

**Comment by yarakhater** [comment]
@IanMGriff  @atosystem any solution?

**Comment by xuan197** [comment]
@ayushnoori  I also encountered the same problem, which will lead to the problem of reproducing the grapher later. How do you solve it？
