### ISSUE TITLE
TrOCR: errors in torch.hub.load(); HTTPError

### ISSUE THREAD

**Issue by EriCongMa** [facebookresearch/fairseq#3972]
Thanks for releasing nice Transformer OCR models.

However, when I tried to run the evaluation scripts, I faced the following error information:

```shell
Downloading: "https://github.com/pytorch/fairseq/archive/master.zip" to /data/cma/.cache/torch/hub/master.zip
...
...
urllib.error.HTTPError: HTTP Error 404: Not Found
```

When I tried to open the link https://github.com/pytorch/fairseq/archive/master.zip in my browser, I found it is now unavailable.

I also tried to add ":main" like
```python
roberta = torch.hub.load('pytorch/fairseq:main', 'roberta.large')
```

It shows that it could be downloaded, but the model parameter setting is different in main repo. compared with master repo.

Could any please help me to solve this problem?

Thanks a lot.

**Comment by AdaUchendu** [comment]
Hi EriCongMa, were you able to figure this out? I have the same problem. 

Thank you

**Comment by EriCongMa** [comment]
> 

I now use TrOCR in hugging face. Maybe you can try TrOCR in hugging face, that version works!
