### ISSUE TITLE
NormFormer: attention scale coefficients

### ISSUE THREAD

**Issue by Fadeich** [facebookresearch/fairseq#3973]
Hello, @sshleifer

I looked into implementation of NormFormer and I have some questions about the scale coefficient for each attention head. 

In the implementation coefficients are applied after full self_attn function (so **out_proj** is applied as well): https://github.com/pytorch/fairseq/blob/c5ff181125c7e6126b49a85e5ebdd5f5b6a07914/fairseq/modules/transformer_layer.py#L368-L381

However, in the paper HeadScaleMHA coefficients are applied **before W^0** (page 3):
HeadScaleMHA = Concat(gamma_1 * h_1, ..., gamma_n * h_n) @ W^0

1. Why are these two approaches equivalent?
2. Is it correct that you learn bias along with W^0?
3. Why do we swap dimensions h and d in einsum (we do 'tbhd,h->tbdh' rather than 'tbhd,h->tbhd')?

Thanks for your implementation!

**Comment by sshleifer** [comment]
Great Q!

I tried to explain in the end of section 2 of the [end of page 4](https://arxiv.org/pdf/2110.09456.pdf) that you can move the head scaling out of the self attention to after W^O to get a little speedup without impacting performance (+-.02 ppl for language modeling). 

To answer your specific questions:
1) They are not mathematically equivalent. I'm happy to share code that lines up with the page 3 math you reference if that's useful to you.
2) `fairseq` by default uses bias with W^0 and we don't modify that behavior, so yes.
3) Will update this post with an answer tomorrow.

**Comment by sshleifer** [comment]
I reviewed/tested the einsum question and the transpose is probably my mistake. Empirically it looks irrelevant.  At 125M params, 49K updates (baseline: 24.20, normformer: 23.279, normformer without transpose: 23.279) and the speeds are within expected ranges.

**Comment by Fadeich** [comment]
Thank you for your response!

> Empirically it looks irrelevant.

We have residual_connection with mixed up values (due to einsum). It seems like it would affect quality of the model or am I missing something?

Also, have you tried [rotary embeddings](https://arxiv.org/pdf/2104.09864.pdf) with NormFormer modifications?

**Comment by sshleifer** [comment]
> We have residual_connection with mixed up values (due to einsum). It seems like it would affect quality of the model or am I missing something?

It's before the residual connection, but there is definitely some mixing going on. Ultimately its an empirical question. The end result was that the transpose fix improved PPL by .07, and makes more sense, so I'll update the code.

> Also, have you tried rotary embeddings with NormFormer modifications?

Nope!
