### ISSUE TITLE
Code requests for the paper "Large-Scale Self- and Semi-Supervised Learning for Speech Translation"

### ISSUE THREAD

**Issue by dearchill** [facebookresearch/fairseq#3980]
Hi, I just read your paper "Large-Scale Self- and Semi-Supervised Learning for Speech Translation", and found it very interesting and helpful, but I can't find the code in the reference url. So will you release the code soon? And I'm looking forward for that.

**Comment by kahne** [comment]
Hi @dearchill , thanks for your interest! Yes, we are working on it. We will let you know when it's available.

**Comment by dearchill** [comment]
> Hi @dearchill , thanks for your interest! Yes, we are working on it. We will let you know when it's available.

Thanks very much.
