### ISSUE TITLE
Fairseq OOM when using multi-GPUs

### ISSUE THREAD

**Issue by lxx909546478** [facebookresearch/fairseq#3981]
# Fairseq OOM when using multi-GPUs
## I run bart-large on my device, if I use 4\*2080ti(4\*12G), it will OOM. And it works well on 1\*3090(24G). I found that it will use more than 12G each GPU even on multi-GPUs. If there is any way for me to run it on my 4\*2080ti(4\*12G)?

**Comment by lxx909546478** [comment]
If there is any way to make it use lower 12G on each GPU? 
If a program use 16G on one GPU, shouldn't it use 8G on two GPUs? It makes me so confused.

**Comment by 18445864529** [comment]
The batch-size refers to that per GPU. So when changing from 24g to 12g the bsz should be halved.

**Comment by lxx909546478** [comment]
> The batch-size refers to that per GPU. So when changing from 24g to 12g the bsz should be halved.

yep, but I have tried to halve the batch_size to 1, it also doesn't work for me. I would appreciate if you have other solutions.

**Comment by lorelupo** [comment]
This behavior is expected because when you select --batch-size or --max-tokens, they both refer to the BATCH SIZE PER GPU, as suggested by @18445864529 . Logically, a 24G has more capacity than 12G and it can therefore process larger batch sizes, as you are observing. Simply try lowering the batch size until it fits in your 4x12G setting.

**Comment by zhongkang-ustc** [comment]
i suggest: max-tokens 4096 or 2048, max-sentences 128 or 64.  it works on my milti-GPU of 12Gib

**Comment by lxx909546478** [comment]
> This behavior is expected because when you select --batch-size or --max-tokens, they both refer to the BATCH SIZE PER GPU, as suggested by @18445864529 . Logically, a 24G has more capacity than 12G and it can therefore process larger batch sizes, as you are observing. Simply try lowering the batch size until it fits in your 4x12G setting.

In fact, I have tried --batch-size=1, but it doesn't work for me.

**Comment by lxx909546478** [comment]
> i suggest: max-tokens 4096 or 2048, max-sentences 128 or 64. it works on my milti-GPU of 12Gib

Thanks for your reply, the setting maybe work for your dataset, but it doesn't work for me.

**Comment by lorelupo** [comment]
> > This behavior is expected because when you select --batch-size or --max-tokens, they both refer to the BATCH SIZE PER GPU, as suggested by @18445864529 . Logically, a 24G has more capacity than 12G and it can therefore process larger batch sizes, as you are observing. Simply try lowering the batch size until it fits in your 4x12G setting.
> 
> In fact, I have tried --batch-size=1, but it doesn't work for me.

There might be a very long sequence in your dataset that causes that OOM even when it is the only sequence in the batch.  Can you check if this is the case?

**Comment by lxx909546478** [comment]
> > > This behavior is expected because when you select --batch-size or --max-tokens, they both refer to the BATCH SIZE PER GPU, as suggested by @18445864529 . Logically, a 24G has more capacity than 12G and it can therefore process larger batch sizes, as you are observing. Simply try lowering the batch size until it fits in your 4x12G setting.
> > 
> > 
> > In fact, I have tried --batch-size=1, but it doesn't work for me.
> 
> There might be a very long sequence in your dataset that causes that OOM even when it is the only sequence in the batch. Can you check if this is the case?

I set --max_tokens to 1000, if it is too large? But when I set it to 800, it will report error "Max sentence length shouldn't exceed 800".

**Comment by 18445864529** [comment]
> > The batch-size refers to that per GPU. So when changing from 24g to 12g the bsz should be halved.
> 
> yep, but I have tried to halve the batch_size to 1, it also doesn't work for me. I would appreciate if you have other solutions.

I would suggest first using `nvidia-smi` to check the memory usage before running, if there are already memory occupations, use `top` to kill the processes. The fairseq trainer has an argument 'raise_oom', if this is set false(by default), it will try to recover from the OOM, in my case, it had never succeeded in recovering but only resulted in dead processes that occupied most of the memories. As a result, once you got OOM, you are very likely to encounter OOM again as long as you don't clear the dead process manually. Anyway, I suggest setting this argument to be True, it can save you a lot of trouble.

**Comment by lorelupo** [comment]
It looks like you have sentences longer than 800 tokens in your dataset.

If your GPU memory is clean already (see @18445864529 comment), I would try to clean your dataset from long sentences, although I am not sure that this would solve your issue, since 1000 tokens shouldn't be too many.
