### ISSUE TITLE
how to convert model in transformers to fairseq.

### ISSUE THREAD

**Issue by holyma** [facebookresearch/fairseq#3993]
I have read this issue 'Converting transformer-LM (GPT2) trained by fairseq to huggingface transformers' #1354, there are some solutions about converting checkpoint of fairseq  to transformers, but I don' t how to convert model in transformers to fairseq, such as how to fintune this pretrained model ([wav2vec-viet](https://huggingface.co/dragonSwing/wav2vec2-base-pretrain-vietnamese) )in fairseq. 

looking forward some helps.

**Comment by shunyuzh** [comment]
Hi, @dreamermary. Have you addressed it? I faced the same problem as you.

**Comment by KushATrivedi** [comment]
Hey @holyma @shunyuzh . Were you able to find a solution or workaround for this? Any insights would be greatly appreciated! Thanks!
