### ISSUE TITLE
Speech-to-text preprocessing copies tuple for 2**15 times instead of doing 16-bit conversion 

### ISSUE THREAD

**Issue by George0828Zhang** [facebookresearch/fairseq#4036]
## 🐛 Bug

In [extract_fbank_features](https://github.com/pytorch/fairseq/blob/7f5ec30b25d906b564cc0ee0e50d1d9193940f58/examples/speech_to_text/data_utils.py#L85) of `examples/speech_to_text/data_utils.py`, this line supposedly converts the waveform to 16-bit signed integer:
```python
    # Kaldi compliance: 16-bit signed integers
    _waveform = _waveform * (2 ** 15)
    _waveform = _waveform[0].numpy()
```
however, `_waveform` as returned by [convert_waveform](https://github.com/pytorch/fairseq/blob/7f5ec30b25d906b564cc0ee0e50d1d9193940f58/fairseq/data/audio/audio_utils.py#L20) is **actually a tuple**, this basically repeats the tuple for 2**15 times...  which does not change the content of the waveform at all ! (and possibly wastes lots of memory)

### To Reproduce

Run any prep_*_data.py and examine the extracted features, the numbers are extremely negative.

#### Code sample

```python
import torchaudio
from fairseq.data.audio.audio_utils import convert_waveform

waveform, sr = torchaudio.load("/some/path/to.mp3")
_waveform = convert_waveform(waveform, sr, to_mono=True)
_waveform = _waveform * (2 ** 15)  # tuple multiplication...
print(_waveform)
```

### Expected behavior

`_waveform` is expected to be in the range of 16-bit signed integer after this multiplication.

### Environment

 - fairseq Version (e.g., 1.0 or main):
 - PyTorch Version (e.g., 1.0)
 - OS (e.g., Linux):
 - How you installed fairseq (`pip`, source):
 - Build command you used (if compiling from source):
 - Python version:
 - CUDA/cuDNN version:
 - GPU models and configuration:
 - Any other relevant information:

**Comment by George0828Zhang** [comment]
I think the simple fix is to swap the two lines:
```python
    _waveform = _waveform[0].numpy()
    _waveform = _waveform * (2 ** 15)
```
I have tested this fix myself.

**Comment by George0828Zhang** [comment]
Hi @kahne, could you take a look at this? Much appreciated.

**Comment by holyma** [comment]
this is a bug. I have run this to extract features, and then run S2T in mustc, I got a low(2+) BLEU. I have compared the previous functions(extract_feature), found that they are different and results are also different .

**Comment by gegallego** [comment]
This was solved in commit [98ebe](https://github.com/pytorch/fairseq/commit/98ebe4f1ada75d006717d84f9d603519d8ff5579). It can be closed, right?
