### ISSUE TITLE
What is prev_output_tokens in TransformerModelBase?

### ISSUE THREAD

**Issue by GaurangTandon** [facebookresearch/fairseq#4041]
## ❓ Questions and Help

I have searched the issues and have searched the docs.

#### What is your question?

I'm training a custom model which inherits from `fairseq.models.transformer.TransformerModel`. I have replaced the encoder and decoder with my own custom encoders/decoders, and now am training the new obtained model with pytorch lightning. It seems I have to provide three arguments to the forward method: `src_tokens`, `src_lengths`, `prev_output_tokens`. Can you please clarify what the third argument is?

It seems to me that we've to train this like an RNN (word by word). But that cannot be the case because the whole premise of transformers was to remove the recurrence equation from RNNs that had made optimizations basically impossible.

So please clarify what that argument means. [Link to the specific line number in the specific file (`TransformerModelBase`) that I am concerned with](https://github.com/pytorch/fairseq/blob/main/fairseq/models/transformer/transformer_base.py#L135).

#### Code

```
    # TorchScript doesn't support optional arguments with variable length (**kwargs).
    # Current workaround is to add union of all arguments in child classes.
    def forward(
        self,
        src_tokens,
        src_lengths,
        prev_output_tokens,
        return_all_hiddens: bool = True,
        features_only: bool = False,
        alignment_layer: Optional[int] = None,
        alignment_heads: Optional[int] = None,
    ):
        """
        Run the forward pass for an encoder-decoder model.
        Copied from the base class, but without ``**kwargs``,
        which are not supported by TorchScript.
        """
        ...
```

#### What have you tried?

Ctrl-F on several places but couldn't find anything.

**Comment by rewicks** [comment]
The `prev_output_tokens function` functions as the target sequence. The naming conventions of `prev_output_tokens` is only used to match auto-regressive models that also exist in fairseq (RNN/LSTM as you mentioned). This also makes more sense during iterative decoding (at inference time).
