### ISSUE TITLE
[Wav2Vec2] Zero-shot Transfer model on Common Voice - Phonetisaurus phonetizer

### ISSUE THREAD

**Issue by patrickvonplaten** [facebookresearch/fairseq#4046]
## Question

Hey Quintong, @alexeib, @michaelauli,

Thanks a lot for open-sourcing the model weights of your recent paper [Simple and Effective Zero-shot Cross-lingual Phoneme Recognition](https://arxiv.org/abs/2109.11680)! 

I've been playing around with the models that use the [`Phonetisaurus`](https://github.com/AdolfVonKleist/Phonetisaurus) phonetizer, but didn't manage to get the phonetizer running correctly. From reading the docs and this example:

```
phonetisaurus-apply --model train/model.fst --word_list test.wlist
```

it seems like a phonetization model in `.fst` format is needed. Is this the case? Do you by any chance add a command that can correctly phonetize an input text sequence somewhere?

Thanks a lot!

**Comment by xuqiantong** [comment]
Hey Patrick, you are right! You can find the `fst`s as well as the running commands in [this repo](https://github.com/uiuc-sst/g2ps/).

**Comment by BakingBrains** [comment]
@xuqiantong @patrickvonplaten Can you please suggest, How can I run the inference for XLSR-53 model using the model and dict provided [here](https://github.com/pytorch/fairseq/tree/main/examples/wav2vec#fine-tune-a-pre-trained-model-with-ctc) with Phonetisaurus, if possible also the steps to train the model using Phonemizer
