### ISSUE TITLE
Scoring with sacrebleu broken with sacrebleu>=2.

### ISSUE THREAD

**Issue by erip** [facebookresearch/fairseq#4055]
## 🐛 Bug

The `TOKENIZERS` attribute was [removed from `sacrebleu.tokenizers`](https://github.com/mjpost/sacrebleu/commit/078c440168c6adc89ba75fe6d63f0d922d42bcfe#diff-f05d865cb9464a2f95d61f884fc0372fba4969e79fa0fa34a2efbc7dfd9c09a2L25) in the 2.0.0 release, so trying to score when it is installed yields an error.

### To Reproduce

Steps to reproduce the behavior (**always include the command you ran**):

1. `pip install -U sacrebleu`
2. `fairseq-generate --scoring sacrebleu ... 

#### Code sample

N/A

### Expected behavior

No errors. :-)

### Environment

 - fairseq Version (e.g., 1.0 or main): main
 - PyTorch Version (e.g., 1.0) 1.10
 - OS (e.g., Linux): Linux
 - How you installed fairseq (`pip`, source): source
 - Build command you used (if compiling from source): n/a
 - Python version: n/a
 - CUDA/cuDNN version: n/a
 - GPU models and configuration:n/a
 - Any other relevant information:

**Comment by cromz22** [comment]
I encountered the same problem.
If you are using the 13a tokenizer, changing `fairseq/scoring/tokenizer.py` as follows could be a temporal solution:

- line 36: `from sacrebleu.tokenizers import TOKENIZERS` -> `from sacrebleu.tokenizers.tokenier_13a import Tokenizer13a`
- line 38: comment out
- line 42: `self.tokenizer = TOKENIZERS[tokenizer_type]` -> `self.tokenizer = Tokenizer13a`

**Comment by kahne** [comment]
Thanks for reporting the issue! Please pull the latest code for the fix (commit: https://github.com/pytorch/fairseq/commit/87d0ede93c06f564b7b985c1a9a0489ae946313d).

**Comment by erip** [comment]
Thanks for the fix, but is there a reason to not just pin the supported version? It seems like it will become difficult to support all versions of the dependencies.

**Comment by kahne** [comment]
> Thanks for the fix, but is there a reason to not just pin the supported version? It seems like it will become difficult to support all versions of the dependencies.

V2.0.0 was out only 4 months ago and it's currently the only 2.x version. We want to keep flexibility for now and will deprecate 1.x in the future when most of the users move to 2.x.
