### ISSUE TITLE
Can't find the .code file for ne-en translation model

### ISSUE THREAD

**Issue by noitanec** [facebookresearch/fairseq#4072]
I've trained nepali to english translation model using [flores](https://github.com/facebookresearch/flores/tree/main/floresv1#train-a-baseline-transformer-model). 

Now, I want to generate translation as per [this tutorial](https://github.com/pytorch/fairseq/tree/main/examples/translation#example-usage-torchhub), loading custom model. I can't find the .code file to pass as argument to `bpe_codes=`

**Comment by Stone749990226** [comment]
bump

**Comment by Stone749990226** [comment]
> I've trained nepali to english translation model using [flores](https://github.com/facebookresearch/flores/tree/main/floresv1#train-a-baseline-transformer-model).
> 
> Now, I want to generate translation as per [this tutorial](https://github.com/pytorch/fairseq/tree/main/examples/translation#example-usage-torchhub), loading custom model. I can't find the .code file to pass as argument to `bpe_codes=`

how did you fix it? I have the same problem
