### ISSUE TITLE
wav2vec-u GAN training not converging on Korean dataset

### ISSUE THREAD

**Issue by KimJeongSun** [facebookresearch/fairseq#4077]
### Before asking:
1. search the issues.
2. search the docs.

#### What is your question?
we are trying to train wav2vec-u on Korean data but our GAN model does not converge well. Are the parameters used to train the model presented in the paper the same as those included in the repo? Also, are the parameters for the multilingual GAN the same as the English model?

#### What have you tried?

We successfully replicated the Librispeech experiment with English data. We prepared a Korean wav2vec 2.0 model with the public AI hub Korean dataset, but the GAN model does not converge when trained on this same data.
( it is not decreasing until 150K)
![image](https://user-images.githubusercontent.com/47556641/146160239-e2b4d332-dad8-4729-8313-dbbda512b7a5.png)

We also tried training the GAN using the XLRS model as an encoder using English Librispeech 100 dataset, and it also does not converge well (with hyper parameter range in paper and recipe). The valididation weighted PPL does not fall below ~60.
( it is not decreasing until 150K)
![image](https://user-images.githubusercontent.com/47556641/146159845-4a0d577b-9e4a-46fe-848e-66c226290ce5.png)
![image](https://user-images.githubusercontent.com/47556641/146160039-02ba5823-0576-4e51-a7c6-85e21345e9d7.png)
![image](https://user-images.githubusercontent.com/47556641/146160087-b584f66f-54c7-44b4-a459-219229151907.png)

#### What's your environment?

 - fairseq Version (e.g., 1.0 or main): 1.0.0a0+741fd13
 - PyTorch Version (e.g., 1.0): 1.8.0+cu111
 - OS (e.g., Linux): ubuntu 20.04
 - How you installed fairseq (`pip`, source): git clone https://github.com/pytorch/fairseq.git && cd fairseq && git reset --hard 741fd138c69eebc1fac09b590047da85cdeafe2
 - Build command you used (if compiling from source): python3 -m pip install --editable ./
 - Python version: 3.8.10
 - CUDA/cuDNN version: cuda_11.1
 - GPU models and configuration: A100 x 8
 - Any other relevant information:

**Comment by lsrami** [comment]
@KimJeongSun  Hello, I have the same problem with wav2vec-u experiment on the Mandarin data set. I guess it may be related to GAN's training hyperparameter settings, but I have adjusted the hyperparameters many times and have not achieved reasonable results. If you have new progress, please share it.

**Comment by XR1988** [comment]
Thanks for your work. What's the current status? I'm not getting good results; my UER is stuck around 90.
I've cloned this repo (it might have environment problems new): https://github.com/oneapi-src/ai-transcribe
Others cloned it with a virtual environment: https://github.com/voidful/wav2vec-u-exp
I'm having trouble with this: https://github.com/facebookresearch/fairseq/issues/5572

**Comment by XR1988** [comment]
Thanks for your work. What's the current status? I'm not getting good results; my UER is stuck around 90.
I've cloned this repo (it might have environment problems new): https://github.com/oneapi-src/ai-transcribe
Others cloned it with a virtual environment: https://github.com/voidful/wav2vec-u-exp
I'm having trouble with this: https://github.com/facebookresearch/fairseq/issues/5572
@KimJeongSun
