### ISSUE TITLE
❓ Preprocessing of Reddit TIFU for BART/BART-RXF

### ISSUE THREAD

**Issue by PhMeier** [facebookresearch/fairseq#4083]
Hello,

thanks for providing the code for the BART-RXF model!
I am trying to reproduce the results from the paper "Better Fine-Tuning by Reducing Representational Collapse" (https://arxiv.org/pdf/2008.03156.pdf) with the BART-RXF/BART on Reddit_tifu.
For now I am using the provided dataset from the paper "Extractive Summarization as Text Matching" (https://github.com/maszhongming/MatchSum. The authors provide train, dev and test splits.

Now I have two questions:
- Is the same data split used for the Representational Collapse paper or did you use a "custom" split?
- Is any preprocessing like BPE applied to the reddit data? 

Thank you very much.

@ArmenAg

**Comment by ArmenAg** [comment]
@PhMeier Hey! Apologies for the late response. We use the same split that is available in the huggingface RedditTIFU dataset, specifically the short version. And yes you will need to apply the same pre-processing that is described here: https://github.com/pytorch/fairseq/blob/main/examples/bart/README.summarization.md

Let me know if you need any more help!

**Comment by PhMeier** [comment]
Dear Armen,

thank you very much for your kind reply, i really appreciate that!

Great to hear about the preprocessing.

Unfortunately I only find a "train" split on the huggingface website (https://huggingface.co/datasets/reddit_tifu) and no "test" split, maybe I missed something.

**Comment by sajastu** [comment]
@ArmenAg  Hi Armen, 

Any update on this? I see that there is a PR for the RXF model on the sentence prediction task, is it useable for summarization (BART) as well? I can't find a similar script for summarization...

**Comment by sajastu** [comment]
Another question, @ArmenAg the huggingface [doesn't provide splits for the Reddit_TIFU dataset](https://huggingface.co/datasets/reddit_tifu). It only has the training split, for both long and short versions. I assume you have used the 80-10-10 split suggested by Pegasus authors for the purpose of training and validation, right? This pops into my mind as you've compared the performance with the Pegasus model.
