### ISSUE TITLE
Training Levenshtein Model - AssertionError: Source and target must contain the same number of examples

### ISSUE THREAD

**Issue by RamoramaInteractive** [facebookresearch/fairseq#4101]
### Before asking:
1. search the issues.
2. search the docs.

I need help how to process the data correctly so that I can train the Levenshtein model.
#### Code

As data I used the europarl.v7 and news-commentary2013 corpuses according to
- [Training Neural Machine Translation To Apply Terminology Constraints](https://arxiv.org/pdf/1906.01105.pdf) (Dinu et al., 2019) [1]
- [Lexically Constrained Neural Machine Translation with Levenshtein Transformer](https://arxiv.org/pdf/2004.12681.pdf) (Susanto et al., 2020) [2]

Train and validation data were already processed according to https://awslabs.github.io/sockeye/tutorials/multilingual.html

This is how I binarized my train and validation (dev) data for the Levenshtein Model:
`fairseq-preprocess --source-lang en --target-lang de --trainpref data/train --validpref data/valid --workers 20 --destdir fairseqdata --joined-dictionary;`

This is how I trained the Levenshtein model:
```
fairseq-train \
    fairseqdata/ \
    --save-dir fairseqdata/checkpoints \
    --encoder-learned-pos \
    --decoder-learned-pos \
    --encoder-attention-heads 8 \
    --decoder-attention-heads 8 \
    --encoder-embed-dim 512 \
    --decoder-embed-dim 512 \
    --encoder-ffn-embed-dim 2048 \
    --decoder-ffn-embed-dim 2048 \
    --ddp-backend=legacy_ddp \
    --task translation_lev \
    --criterion nat_loss \
    --arch levenshtein_transformer \
    --noise random_delete \
    --share-all-embeddings \
    --optimizer adam --adam-betas '(0.9,0.98)' \
    --lr 0.005 --lr-scheduler inverse_sqrt \
    --stop-min-lr '1e-09' --warmup-updates 10000 \
    --warmup-init-lr '1e-07' --label-smoothing 0.1 \
    --dropout 0.3 --weight-decay 0.01 \
    --encoder-layers 6 \
    --decoder-layers 6 \
    --apply-bert-init \
    --log-format 'simple' --log-interval 100 \
    --fixed-validation-seed 7 \
    --max-tokens 64000 \
    --save-interval-updates 10000 \
    --max-update 300000 &
```

#### What have you tried?

I already tried to concat the europarl and news-commentary data in source and target respectively. It doesn't worked. I have no idea how to solve this error.

**Comment by kkeleve** [comment]
> ## ❓ Questions and Help
> ### Before asking:
> 1. search the issues.
> 2. search the docs.
> 
> I need help how to process the data correctly so that I can train the Levenshtein model.
> 
> #### What is your question?
> #### Code
> As data I used the europarl.v7 and news-commentary2013 corpuses according to
> 
> * [Training Neural Machine Translation To Apply Terminology Constraints](https://arxiv.org/pdf/1906.01105.pdf) (Dinu et al., 2019) [1]
> * [Lexically Constrained Neural Machine Translation with Levenshtein Transformer](https://arxiv.org/pdf/2004.12681.pdf) (Susanto et al., 2020) [2]
> 
> Train and validation data were already processed according to https://awslabs.github.io/sockeye/tutorials/multilingual.html
> 
> This is how I binarized my train and validation (dev) data for the Levenshtein Model: `fairseq-preprocess --source-lang en --target-lang de --trainpref data/train --validpref data/valid --workers 20 --destdir fairseqdata --joined-dictionary;`
> 
> This is how I trained the Levenshtein model:
> 
> ```
> fairseq-train \
>     fairseqdata/ \
>     --save-dir fairseqdata/checkpoints \
>     --encoder-learned-pos \
>     --decoder-learned-pos \
>     --encoder-attention-heads 8 \
>     --decoder-attention-heads 8 \
>     --encoder-embed-dim 512 \
>     --decoder-embed-dim 512 \
>     --encoder-ffn-embed-dim 2048 \
>     --decoder-ffn-embed-dim 2048 \
>     --ddp-backend=legacy_ddp \
>     --task translation_lev \
>     --criterion nat_loss \
>     --arch levenshtein_transformer \
>     --noise random_delete \
>     --share-all-embeddings \
>     --optimizer adam --adam-betas '(0.9,0.98)' \
>     --lr 0.005 --lr-scheduler inverse_sqrt \
>     --stop-min-lr '1e-09' --warmup-updates 10000 \
>     --warmup-init-lr '1e-07' --label-smoothing 0.1 \
>     --dropout 0.3 --weight-decay 0.01 \
>     --encoder-layers 6 \
>     --decoder-layers 6 \
>     --apply-bert-init \
>     --log-format 'simple' --log-interval 100 \
>     --fixed-validation-seed 7 \
>     --max-tokens 64000 \
>     --save-interval-updates 10000 \
>     --max-update 300000 &
> ```
> 
> #### What have you tried?
> I already tried to concat the europarl and news-commentary data in source and target respectively. It doesn't worked. I have no idea how to solve this error.

hi, have you resolved this issue?
