### ISSUE TITLE
How to use special tokens in bpe or binarize stage

### ISSUE THREAD

**Issue by kugwzk** [facebookresearch/fairseq#4103]
#### What is your question?

When I follow the BART summarization readme ([https://github.com/pytorch/fairseq/blob/main/examples/bart/README.summarization.md](url)), I find the bpe and binarize process not consider the special tokens in input files, such as `<s>`.
Does there any way to add the special token during the preprocess? 
Thanks.

**Comment by nikhiljaiswal** [comment]
@kugwzk I have also got the same issue. Did you find any leads?
