### ISSUE TITLE
Simultaneous Speech Translation Training

### ISSUE THREAD

**Issue by woong97** [facebookresearch/fairseq#4113]
I'm following Simultaneous Speech Translation Training. 
https://github.com/pytorch/fairseq/blob/main/examples/speech_to_text/docs/simulst_mustc_example.md

But When I execute this command in documentation, error occured.
```C
 fairseq-train ${MUSTC_ROOT}/en-de \
        --config-yaml config_st.yaml --train-subset train_st --valid-subset dev_st \
        --save-dir ${ST_SAVE_DIR} --num-workers 8  \
        --optimizer adam --lr 0.0001 --lr-scheduler inverse_sqrt --clip-norm 10.0 \
        --criterion label_smoothed_cross_entropy \
        --warmup-updates 4000 --max-update 100000 --max-tokens 40000 --seed 2 \
        --load-pretrained-encoder-from ${ASR_SAVE_DIR}/checkpoint_best.pt \
        --task speech_to_text  \
        --arch convtransformer_simul_trans_espnet  \
        --simul-type waitk_fixed_pre_decision  \
        --waitk-lagging 3 \
        --fixed-pre-decision-ratio 7 \
        --update-freq 8
```

```
fairseq-train: error: argument --simul-type: inivalid choice: 'waitk_fixed_pred_decision'
```
Please help me how to fix this.

**Comment by duj12** [comment]
@woong97 Hello, how did you solve this problem? I met a similar problem, it's like:
fairseq-train: error: argument ---arch: inivalid choice: 'convtransformer_simul_trans_espnet'.

I added '--user-dir examples/simultaneous_translation', then it can find the arch, but this cause the following errors:

`

> Traceback (most recent call last):
>   File "/data/dujing6/miniconda/envs/fairseq/bin/fairseq-train", line 33, in <module>
>     sys.exit(load_entry_point('fairseq', 'console_scripts', 'fairseq-train')())
>   File "/data/dujing6/fairseq-main/fairseq_cli/train.py", line 493, in cli_main
>     parser = options.get_training_parser()
>   File "/data/dujing6/fairseq-main/fairseq/options.py", line 38, in get_training_parser
>     parser = get_parser("Trainer", default_task)
>   File "/data/dujing6/fairseq-main/fairseq/options.py", line 227, in get_parser
>     utils.import_user_module(usr_args)
>   File "/data/dujing6/fairseq-main/fairseq/utils.py", line 489, in import_user_module
>     importlib.import_module(module_name)
>   File "/data/dujing6/miniconda/envs/fairseq/lib/python3.8/importlib/__init__.py", line 127, in import_module
>     return _bootstrap._gcd_import(name[level:], package, level)
>   File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
>   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
>   File "<frozen importlib._bootstrap_external>", line 848, in exec_module
>   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
>   File "/data/dujing6/fairseq-main/examples/simultaneous_translation/__init__.py", line 6, in <module>
>     from . import models  # noqa
>   File "/data/dujing6/fairseq-main/examples/simultaneous_translation/models/__init__.py", line 13, in <module>
>     importlib.import_module(
>   File "/data/dujing6/miniconda/envs/fairseq/lib/python3.8/importlib/__init__.py", line 127, in import_module
>     return _bootstrap._gcd_import(name[level:], package, level)
>   File "/data/dujing6/fairseq-main/examples/simultaneous_translation/__init__.py", line 6, in <module>
>     from . import models  # noqa
>   File "/data/dujing6/fairseq-main/examples/simultaneous_translation/models/__init__.py", line 13, in <module>
>     importlib.import_module(
>   File "/data/dujing6/miniconda/envs/fairseq/lib/python3.8/importlib/__init__.py", line 127, in import_module
>     return _bootstrap._gcd_import(name[level:], package, level)
>   File "/data/dujing6/fairseq-main/examples/simultaneous_translation/models/convtransformer_simul_trans.py", line 26, in <module>
>     from fairseq.models.speech_to_text.modules.emformer import NoSegAugmentedMemoryTransformerEncoderLayer
>   File "/data/dujing6/fairseq-main/fairseq/models/speech_to_text/modules/emformer.py", line 30, in <module>
>     from torch.ao.quantization.qconfig import (
> ModuleNotFoundError: No module named 'torch.ao'

`

I install fairseq with “pip install --editable ./”, and
torch=1.7+cu92
python=3.8

It seems the version of torch is not compatible? But I use this version for quite a long time, and it works fine with Speech_to_Text task.
I don't know which version of torch is proper to "fairseq/models/speech_to_text/modules/emformer.py"
