### ISSUE TITLE
Installing Fairseq from source on Colab fails ( ImportError: cannot import name <> from 'fairseq' (unknown location)

### ISSUE THREAD

**Issue by gowtham1997** [facebookresearch/fairseq#4121]
## 🐛 Bug

I am trying to install Fairseq from the source on colab and it seems to be running into import errors.

[Here](https://colab.research.google.com/drive/1EdFPAvlG69hpTsKxDPKg2dreMtI_LKrR?usp=sharing) is a reproducible colab notebook. 

I also tried adding cloned location to PYTHONPATH as suggested [here](https://github.com/pytorch/fairseq/issues/2546) but that doesn't seem to work as well.

**Comment by chevalierNoir** [comment]
Installing fairseq under normal mode should work: ! pip install ./

**Comment by gowtham1997** [comment]
Great.This works

Thanks

**Comment by zhaoguangxiang** [comment]
How can we avoid this bug in the editable mode?

**Comment by ustcwhy** [comment]
> How can we avoid this bug in the editable mode?

do you resolve this issue ?

**Comment by zhaoguangxiang** [comment]
> Installing fairseq under normal mode should work: ! pip install ./

I did not resolve it.

**Comment by avidale** [comment]
I have the same issue in editable mode on the NLLB branch in Colab notebook. 

I rune the following for installation (adapted from the NLLB installation guide https://github.com/facebookresearch/fairseq/blob/nllb/INSTALL.md):
```
!git clone https://github.com/pytorch/fairseq #  && cd fairseq && pip install --editable ./ 
!cd fairseq && git checkout nllb && pip install -e . && python setup.py build_ext --inplace
! git clone https://github.com/facebookresearch/fairscale.git && cd fairscale && git checkout origin/experts_lt_gpus_moe_reload_fix && pip install -e .
```

Then I apply a fix to the path for Google Colab, as suggested here: https://github.com/facebookresearch/fairseq/issues/2546
```
import os
os.environ['PYTHONPATH'] += ":/content/fairseq/"
os.environ['PYTHONPATH'] += ":/content/fairscale/"
```

Then I try some importing
```
from fairseq import checkpoint_utils
```
and get an error
```
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
[<ipython-input-6-2849b72f6821>](https://localhost:8080/#) in <cell line: 1>()
----> 1 from fairseq import checkpoint_utils

1 frames
[/content/fairseq/fairseq/moe_checkpoint_utils.py](https://localhost:8080/#) in <module>
     15 from fairscale.nn.data_parallel.fsdp_optim_utils import is_singleton_tensor
     16 
---> 17 from fairseq import distributed_utils
     18 from fairseq.file_io import torch_load_cpu
     19 

ImportError: cannot import name 'distributed_utils' from 'fairseq' (unknown location)

---------------------------------------------------------------------------
NOTE: If your import is failing due to a missing package, you can
manually install dependencies using either !pip or !apt.

To view examples of installing some common dependencies, click the
"Open Examples" button below.
---------------------------------------------------------------------------
```

**Comment by avidale** [comment]
@gowtham1997 please reopen!
