### ISSUE TITLE
Evaluation Error: TypeError: forward() missing 1 required positional argument: 'prev_output_tokens'

### ISSUE THREAD

**Issue by fenimi** [facebookresearch/fairseq#4139]
## ❓ Questions and Help
I added a new classification task using the transformer model. This is what my code looks like:
`import os
import torch

from fairseq.data import Dictionary, LanguagePairDataset
from fairseq.tasks import FairseqTask, register_task

@register_task('simple_classification')
class SimpleClassificationTask(FairseqTask):

    @staticmethod
    def add_args(parser):
        #Add some command-line arguments for specifying where the data is located and the maximum supported input length.
        parser.add_argument('data', metavar='FILE', help='file prefix for data')
        parser.add_argument('--max-positions', default=1024, type=int, help='max input length')

    @classmethod
    def setup_task(cls, args, **kwargs):
        #Here we can perform any setup required for the task. This may include loading Dictionaries, initializing shared
        #Embedding layers, etc. In this case we'll just load the dictionaries.
        input_vocab = Dictionary.load(os.path.join(args.data, 'dict.input.txt'))
        label_vocab = Dictionary.load(os.path.join(args.data, 'dict.label.txt'))
        print('| [input] dictionary: {} types'.format(len(input_vocab)))
        print('| [label] dictionary: {} types'.format(len(label_vocab)))

        return SimpleClassificationTask(args, input_vocab, label_vocab)

    def __init__(self, args, input_vocab, label_vocab):
        super().__init__(args)
        #self.args = args
        self.input_vocab = input_vocab
        self.label_vocab = label_vocab
    def load_dataset(self, split, **kwargs):
        """ Load a given dataset split (e.g., train, dev, test."""

        prefix = os.path.join(self.cfg.data, '{}.input-label'.format(split))

        # Read input sentences.
        sentences, lengths = [], []
        with open(prefix + '.input', encoding='utf-8') as file:

            for line in file:
                sentence = line.strip()

                #Tokenize the sentence, splitting on spaces
                tokens = self.input_vocab.encode_line(sentence, add_if_not_exist=False,)
                sentences.append(tokens)
                lengths.append(tokens.numel())

        # Read labels.
        labels = []
        with open(prefix + '.label', encoding='utf-8') as file:
            for line in file:
                label = line.strip()
                labels.append(
                    # Convert labels to a numeric ID.
                    torch.LongTensor([self.label_vocab.add_symbol(label)])
                )
        assert len(sentences) == len(labels)
        print('| {} {} {} example'.format(self.cfg.data, split, len(sentences)))

        # We reuse LanguagePairDataset since classification can be modeled as a
        # sequence-to-sequence task where the target sequence has length 1.

        self.datasets[split] = LanguagePairDataset(
            src=sentences,
            src_sizes=lengths,
            src_dict=self.input_vocab,
            tgt=labels,
            tgt_sizes=torch.ones(len(labels)), #targets have length 1
            tgt_dict=self.label_vocab,
            left_pad_source=False,
            # Since our target is a single class label, there's no need for
            # teacher forcing. If we set this to "True" then our Model's
            # "forward()" method would receive an additional argument called
            # *prev_output_tokens* that would contain a shifted version of the
            # target sequence.
            input_feeding=True,
        )
    def max_positions(self):
     #   """ Return the max input length allowed by the task."""
       # The source should be less than *args.max_positions and the "target"
        # has max length 1.
        return (self.cfg.max_positions, 1)

    @property
    def source_dictionary(self):
        """ Return the max input length allowed by the task."""
        return self.input_vocab
    @property
    def target_dictionary(self):
        """ Return the max input length allowed by the task."""
        return self.label_vocab`

Which runs well, but evaluation returns an error:

`
TypeError:forward() missing 1 required positional argument: 'prev_output_tokens'
`

This is what the evaluation code looks like:

```
from fairseq import checkpoint_utils, data, options, tasks
 # Parse command-line arguments for generation
 parser = options.get_generation_parser(default_task='simple_classification')
 args = options.parse_args_and_arch(parser)
 # Setup task
 task = tasks.setup_task(args)
 # Load model
 print('| loading model from {}'.format(args.path))
 models, _model_args = checkpoint_utils.load_model_ensemble([args.path], task=task)
 model = models[0]
 print(model)
 while True:
    sentence = input('\nInput: ')
    # Tokenize into characters
    chars = ' '.join(list(sentence.strip()))
    tokens = task.source_dictionary.encode_line(chars, add_if_not_exist=True,
    )
   
    # Build mini-batch to feed to the model
    batch = data.language_pair_dataset.collate(
        samples=[{'id': -1, 'source': tokens}],  # bsz = 1
        pad_idx=task.source_dictionary.pad(),
        eos_idx=task.source_dictionary.eos(),
        left_pad_source=False,
        input_feeding=True,)
   
    # Feed batch to the model and get predictions
    print(batch)
    preds, _ = model(**batch['net_input'])
    # Print top 3 predictions and their log-probabilities
    top_scores, top_labels = preds[0].topk(k=3)
    for score, label_idx in zip(top_scores, top_labels):
        label_name = task.target_dictionary.string([label_idx])
        print('({:.2f})\t{}'.format(score, label_name))
```

#### What have you tried?
I set input_feeding=True in evaluation but it doesn't change anything. 
#### What's your environment?

 - fairseq Version (e.g., 1.0 or main): v0.10.2
 - PyTorch Version (e.g., 1.0): Python 3.8.10
 - OS (e.g., Linux): linux
 - How you installed fairseq (`pip`, source): pip 
 - Build command you used (if compiling from source):
 - Python version: '1.10.0'
 - CUDA/cuDNN version: cuda/11.0
 - GPU models and configuration: P100-PCIE
 - Any other relevant information:

**Comment by RuABraun** [comment]
I have this problem too
