### ISSUE TITLE
About the work of data2vec

### ISSUE THREAD

**Issue by taokong** [facebookresearch/fairseq#4147]
Hi Alexei @alexeib ,

Congratulations on the most recent work of data2vec, and the performance of it is really impressive!

However, after carefully reading the main draft, I find that you may have missed one most related prior self-supervised work -- iBOT: Image BERT Pre-Training with Online Tokenizer (https://arxiv.org/abs/2111.07832).

I believe iBOT should be considered to be compared in your work (e.g., masked prediction, latent representation, and context).

Best,

Tao Kong

**Comment by michaelauli** [comment]
Hi Tao,

Thanks for reaching out - we will discuss and compare to your work in the next revision of our paper.

Best,

Michael
