### ISSUE TITLE
How to cite data2vec

### ISSUE THREAD

**Issue by YaoMarkMu** [facebookresearch/fairseq#4151]
Hello,

Thanks for your awesome work, data2vec.

I'd like to cite this work but I can not find the `bib`.

Could provide it?

**Comment by michaelauli** [comment]
We will upload the paper to arXiv shortly. In the meantime, please cite the paper just like GPT-1: 

@Misc{radford2018unsup,
  Title                    = {Improving Language Understanding by Generative Pre-Training},
  HowPublished             = {\url{https://s3-us-west-2.amazonaws.com/openai-assets/research-covers/language-unsupervised/language_understanding_paper.pdf}},
  Author                   = {Alec Radford and Karthik Narasimhan and Tim Salimans and Ilya Sutskever},
  Year                     = {2018},
}
