### ISSUE TITLE
How to use fairseq-hydra-train with multi-nodes?

### ISSUE THREAD

**Issue by Snowdar** [facebookresearch/fairseq#4160]
## ❓ Questions and Help

I do not plan to use srun and just start the training on two machines by hands. But how to use fairseq-hydra-train with multi-nodes? Configure the yaml only or use torchrun? Please help and thanks very much!

**Comment by weiyx16** [comment]
> ## ❓ Questions and Help
> I do not plan to use srun and just start the training on two machines by hands. But how to use fairseq-hydra-train with multi-nodes? Configure the yaml only or use torchrun? Please help and thanks very much!

Here is my [solution](https://github.com/facebookresearch/av_hubert/issues/19). Hope it will be useful.
