### ISSUE TITLE
speech_to_text's example might have a typo

### ISSUE THREAD

**Issue by ZurabDz** [facebookresearch/fairseq#4186]
#### What is your question?
Am I misusing script or do we have a typo?

#### Code
```python3
python fairseq/examples/speech_to_text/prep_librispeech_data.py
```
 
creates an error:
```python3
Traceback (most recent call last):
  File "prep_librispeech_data.py", line 14, in <module>
    from examples.speech_to_text.data_utils import (
ModuleNotFoundError: No module named 'examples'
```
#### What have you tried?
changing source code to:

```python3
from data_utils import (
    create_zip,
    extract_fbank_features,
    gen_config_yaml,
    gen_vocab,
    get_zip_manifest,
    save_df_to_tsv,
)
```
seems to work then...
#### What's your environment?

 - fairseq Version 0.10.2
 - PyTorch Version 1.10.2+cu113
 - OS Debian GNU/Linux 11 (bullseye)
 - How you installed fairseq (`pip`, source): clone source, pip install path/to/fairseq
 - Python version: 3.7.11
 - CUDA/cuDNN version: cu113
 - GPU models and configuration: RTX 3050 TI

**Comment by duj12** [comment]
you may add the path of fairseq root to your PYTHONPATH, input this in shell script:
export PYTHONPYTH=$PYTHONPATH:/path/to/your/fairseq
so that python can find 'examples/speech_to_text/prep_librispeech_data.py' to execute.

**Comment by ZurabDz** [comment]
Yep you are right, sorry didn't think of that.
