### ISSUE TITLE
Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.

### ISSUE THREAD

**Issue by pupil011** [facebookresearch/fairseq#4195]
i want to train a new wav2vec base model, when i run:
**fairseq-hydra-train \
    task.data=/Home/code/guozhi/slr \
    --config-dir ~/Home/code/guozhi/fairseq/examples/wav2vec/config/pretraining \
    --config-name wav2vec2_base_librispeech \
**
there are some error:
**
Additional config directory '/home/gaogzh/Home/code/guozhi/fairseq/examples/wav2vec/config/pretraining' not found

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
**
for why?

**Comment by guobabaya** [comment]
hi，bro. Have you finally solved the problem?

**Comment by pupil011** [comment]
> hi，bro. Have you finally solved the problem?

sure, i used the relative path to solve.

**Comment by Freedomcls** [comment]
> > hi，bro. Have you finally solved the problem?
> 
> sure, i used the relative path to solve.

hi, bro, I also met the same problem, could you please tell me the specific operation, thanks!

**Comment by wccccp** [comment]
> hi, bro, I also met the same problem, could you please tell me the specific operation, thanks!

**Comment by mxahan** [comment]
pip install iopath


worked for me. A similar error was encountered while running the SAM 2 model builder.
