### ISSUE TITLE
All generate.py output(Source sentence, target sentence and Alignment )are all numbers not words 

### ISSUE THREAD

**Issue by sc16s2w** [facebookresearch/fairseq#4208]
#### What have you tried?
I want to print the source sentence, the alignment, the hypothesis, but my output is just shown as follows:
![image](https://user-images.githubusercontent.com/44282471/153661401-f6e93a11-324d-40b8-9720-7ac356fb5f4f.png)
it is difficult for me to connect the score with the original sentence, I just want the output to be the same as the example like this: 
![image](https://user-images.githubusercontent.com/44282471/153661573-aebf1e24-cbc3-405b-9215-f0028b62cbff.png)
Can you tell me how to solve my problem?
#### What's your environment?
 - fairseq Version (0.10.2):
 - PyTorch Version:1.10.2
 - OS (Unix):
 - How you installed fairseq (`pip`):
 - Build command you used (): fairseq-generate  /var/folders/sx/k7w_5wtj571c2c7z348t0yr80000gn/T/tmpbj7fcyxi --dataset-impl raw --gen-subset tmp --path /Users/wangsiwei/Downloads/muss/resources/models/muss_en_wikilarge_mined/model.pt --beam 5 --nbest 1 --lenpen 1.0 --diverse-beam-groups -1 --diverse-beam-strength 0.5 --max-tokens 8000 --model-overrides "{'encoder_embed_path': None, 'decoder_embed_path': None}" --skip-invalid-size-inputs-valid-test --print-alignment 
 - Python version: 3.6
 - CUDA/cuDNN version: no
 - GPU models and configuration: no
 - Any other relevant information: no

**Comment by lyu021** [comment]
I have the same problem when I generate the hypothesis. Have you solved it?

**Comment by sc16s2w** [comment]
> I have the same problem when I generate the hypothesis. Have you solved it?

Yes, please use the encode and decode function to recover.
