### ISSUE TITLE
FSDP fail to train translation model with 1.4B parameters in 32GB V100.

### ISSUE THREAD

**Issue by SefaZeng** [facebookresearch/fairseq#4256]
### Before asking:
1. search the issues.
2. search the docs.

#### What is your question?
FSDP fail to train translation model with 1.4B parameters. But as the example says, it could train a 13B params model with V100.
#### Code
This is the shell script:
```
export CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7
work_dir=/workspace/fairseq/
  
dataname=wmt14_ende
data_dir=$work_dir/${dataname}
fairseq_dir=$work_dir/fairseq-git
output_dir=$work_dir/checkpoints/test
  
OMP_NUM_THREADS=20 \
/home/user/miniconda/bin/python3 $fairseq_dir/train.py \
  $data_dir \
 --task translation \
 --save-dir $output_dir \
 --arch transformer \
 --share-all-embeddings \
 --attention-dropout 0.1 \
 --activation-dropout 0.1 \
 --dropout 0.1 \
 --encoder-layers 200 \
 --decoder-layers 200 \                                                                                                                
 --encoder-embed-dim 512 \
 --decoder-embed-dim 512 \
 --encoder-attention-heads 8 \ 
 --encoder-attention-heads 8 \ 
 --encoder-ffn-embed-dim 2048 \
 --decoder-ffn-embed-dim 2048 \
 --optimizer cpu_adam --adam-betas '(0.9, 0.98)' --adam-eps 1e-8 --clip-norm 0.0 \
 --lr 5e-4 --lr-scheduler inverse_sqrt --warmup-updates 4000 \
 --warmup-init-lr 1e-07 \
 --weight-decay 0.0001 \
 --criterion label_smoothed_cross_entropy --label-smoothing 0.1 \
 --max-tokens 2048 \
 --update-freq 1 \ 
 --log-interval 100 \
 --save-interval-updates 10000 \
 --save-interval 100000000000 \
 --num-workers 1 \ 
 --seed 42 \
 --fp16  \
 --ddp-backend=fully_sharded \
 --cpu-offload \
 --no-reshard-after-forward \
```

#### What's your environment?

 - fairseq Version (e.g., 1.0 or main): 0.10.0(master)
 - PyTorch Version (e.g., 1.0) 1.10.2
 - OS (e.g., Linux): Linux
 - How you installed fairseq (`pip`, source): source
 - Build command you used (if compiling from source):
 - Python version: 3.8
 - CUDA/cuDNN version: 10.2
 - GPU models and configuration:
 - Any other relevant information:

**Comment by SefaZeng** [comment]
`--checkpoint-activations` is needed if you wannt train very large model.

**Comment by gmryu** [comment]
Are you experiencing an `AssertionError: Only flatten param or a single non-shared param is supported: len=0` like this (https://github.com/facebookresearch/fairscale/issues/925)

If it is not, I guess you should at least explain what is failed.
