### ISSUE TITLE
[error][data2vec]omegaconf.errors.ConfigKeyError: Key 'cache_in_scratch' not in 'AudioFinetuningConfig'

### ISSUE THREAD

**Issue by Dawn-970** [facebookresearch/fairseq#4267]
### To Reproduce

Steps to reproduce the behavior (**always include the command you ran**):

1. Run cmd 'fairseq-hydra-train \
    task.normalize=true \
    common.user_dir=/mypath1 \
    distributed_training.distributed_world_size=1 \
    task.data=/mypath2 \
    model.w2v_path=/mypath3 \
    --config-dir /mypath4 \
    --config-name base_100h  '
2. See error
omegaconf.errors.ConfigKeyError: Key 'cache_in_scratch' not in 'AudioFinetuningConfig'
        full_key: cache_in_scratch
        reference_type=Optional[AudioFinetuningConfig]
        object_type=AudioFinetuningConfig

### Environment

 - fairseq Version :main
 - PyTorch Version 1.11.0
 - OS (e.g., Linux): Linux
 - How you installed fairseq (`pip`, source):cloned the main branch from repo
 - Python version:3.8.12

**Comment by Dawn-970** [comment]
I find that I used the wrong model. 
The model.w2v_path should be a no_finetune model ,but I used  a finetuned one.

**Comment by xmz1009** [comment]
@Dawn-970 ，hi，i have the same bug,'omegaconf.errors.ConfigKeyError: Key 'rebuild_batches' not in 'AudioPretrainingConfig'         full_key: rebuild_batches         reference_type=Optional[AudioPretrainingConfig]         object_type=AudioPretrainingConfig'', can you fix it?
