### ISSUE TITLE
Make `fairseq_cli.train` compatible with `torch.distributed.run`

### ISSUE THREAD

**Issue by kiukchung** [facebookresearch/fairseq#4302]
## 🚀 Feature Request
Support launching `fairseq_cli.train` with `torch.distributed.run`. Something of the effect of:

```
$ python -m torch.distributed.run <...omitted for brevity...> fairseq-train <... train args...>
```

### Motivation

`fairseq-train` gets the device_id from either explicit `--device_id` or (the aliased) `--local_rank` CLI argument. `torch.distributed.launch` had a `--use-env=False` option where instead of setting `LOCAL_RANK` env var, it passes `--local_rank` to the training script, which is exactly what `fairseq-train` depended on.

As of torch-1.9+ `torch.distributed.launch` (which fairseq-train supports) has been deprecated in favor of `torch.distributed.run` (aka `torchrun`) (see [docs](https://pytorch.org/docs/stable/distributed.html#launch-utility))

![image](https://user-images.githubusercontent.com/43595115/159797548-126a63e4-8d0b-4487-998c-58f4b4c71b40.png)

The `--use-env` option has been deprecated in `torch.distributed.run` in favor of reading the local_rank from the environment variable `os.environ["LOCAL_RANK"]` instead of the CLI argument `--local_rank`. So for future fairseq releases, its better to read the local_rank from the `LOCAL_RANK` env var rather than from the `--local_rank` CLI argument

### Pitch

Seems like the change is pretty straight forward:

1. Change this line (https://github.com/pytorch/fairseq/blob/main/fairseq/distributed/utils.py#L318) in `fairseq.distributed.utils.distributed_main` to:
    ```
    def distributed_main(i, main, cfg: FairseqConfig, kwargs):
        cfg.distributed_training.device_id = i
        if torch.cuda.is_available() and not cfg.common.cpu and not cfg.common.tpu:
            torch.cuda.set_device(os.getenv("LOCAL_RANK", cfg.distributed_training.device_id))
       <... REST OF THE FUNCTION OMITTED FOR BREVITY...>
    ```

### Alternatives
N/A. Currently users have to either monkey patch `fairseq.distributed.utils.distributed_main` or wrap `fairseq_cli.train` with a custom main module that injects `sys.argv.append(--local_rank=os.environ["LOCAL_RANK"])`

### Additional context
See embedded hyperlinks above.

**Comment by colinclement** [comment]
I suggest this PR which instead just changes the default value in the `fairseq/dataclass/config.py` from `device_id=0` to `os.getenv("LOCAL_RANK", 0)`. This way, if you want to set `device_id` (which so far I have been doing to overcome this issue), that will still work as expected instead of being overwritten by `$LOCAL_RANK` in `distributed_main`.
