### ISSUE TITLE
About classification head of data2vec

### ISSUE THREAD

**Issue by Ramlinbird** [facebookresearch/fairseq#4303]
Sorry to disturb, @alexeib , I read the paper and source code of data2vec, and found that there is [CLS] token for text to do classification directly. But for audio, there is no such summary vector to do whole audio classification. Is there any suggestion? Thanks a lot.

**Comment by alexeib** [comment]
there are a few different things you can do, e.g. mean-pooling the representations from all time-steps and then projecting that into your class labels. for an evaluation check out this paper: https://arxiv.org/abs/1810.09050
