### ISSUE TITLE
--share-all-embeddings requires a joined dictionary

### ISSUE THREAD

**Issue by xiaohangguo** [facebookresearch/fairseq#4325]
### Before asking:
1. search the issues.
2. search the docs.

#### What is your question?
1.Is the error caused by the unequal length of 'de'' and 'en'' dictionaries?
2.I don't know if I use this command line'--joined-dictionary' to solve this problem. If so, how should I use the'--joined-dictionary' command to solve this problem?

#### Code
 delta=1.0
 modelfile=/root/model
 data=/root/data2

>python train.py --ddp-backend=no_c10d ${data} \
 >--arch transformer\
 >--share-all-embeddings \
 >--optimizer adam \
 >--adam-betas '(0.9, 0.98)' \
 >--clip-norm 0.0 \
 >--lr 5e-4 \
 >--lr-scheduler inverse_sqrt \
 >--warmup-init-lr 1e-07 \
 >--warmup-updates 4000 \
 >--dropout 0.3 \
> --criterion label_smoothed_cross_entropy \
> --label-smoothing 0.1 \
> --left-pad-source False \
> --delta ${delta} \
> --save-dir ${modelfile} \
> --max-tokens 4096 --update-freq 2

####Error message:

| [de] dictionary: 34928 types
| [en] dictionary: 33176 types
| loaded 2919 examples from: /root/data2/valid.de-en.de
| loaded 2919 examples from: /root/data2/valid.de-en.en
| /root/data2 valid de-en 2919 examples
Traceback (most recent call last):
  File "/root/GMA/train.py", line 365, in <module>
    cli_main()
  File "/root/GMA/train.py", line 361, in cli_main
    main(args)
  File "/root/GMA/train.py", line 59, in main
    model = task.build_model(args)
  File "/root/GMA/fairseq/tasks/fairseq_task.py", line 201, in build_model
    return models.build_model(args, self)
  File "/root/GMA/fairseq/models/__init__.py", line 48, in build_model
    return ARCH_MODEL_REGISTRY[args.arch].build_model(args, task)
  File "/root/GMA/fairseq/models/transformer.py", line 154, in build_model
    raise ValueError("--share-all-embeddings requires a joined dictionary")
ValueError: --share-all-embeddings requires a joined dictionary

#### What have you tried?
--share-all-embeddings requires a joined dictionary
Do not know how to use this parameter command
#### What's your environment?

 - fairseq Version (1.0 ):
 - PyTorch Version (10.2)
 - OS (Linux):

**Comment by gmryu** [comment]
Well, your suspection is correct:  
> it is the error caused by the unequal length of 'de'' and 'en'' dictionaries

and `--share-all-embeddings` is a strange idea when you want to handle different language.

share all embeddings means TransformerEncoder and TransfomrerDecoder's input embedding has the same dimension.
So if you're translating english to german, encoder's input embedding feature dimension= len(english dict)+4 for eos,bos,unk,pad,   while decoder's feature dimension = len(german dict)+4.
 A joined dictionary only means you copy and paste src and tgt dictionaries into one text, thus src and target dict uses the same dict and have the same size. You can create one by `fairseq-preprocess --joined-dictionary  ...data....` but copy-paste is faster if there are only 2 languages. it is more meant for multilingual task I guess?

**Comment by xiaohangguo** [comment]
First of all, thank you for your reply. I have been trying to add the code>'--join-dictionnary', but it turned out to be wrong. As you said, it would be right to add after >'fairseq-perprocess'. 
Secondly, this German and English translation is a piece of open source code that I run, and the author left out the command to join the dictionary, so I have been trying again and have been very upset. Thank you very much for your help. I solved it yesterday.
Finally, I would like to ask you, does the equation you are talking about have to be satisfied in these two languages, is there a different relationship between other languages, and how is this relationship established?

The one you said is more suitable for multilingual tasks, in fact, I am not quite clear, do you have to implement or think about it? We can discuss it together.

Nice to communicate with you, thank you!

**Comment by gmryu** [comment]
> does the equation you are talking about have to be satisfied in these two languages, is there a different relationship between other languages, and how is this relationship established?

Sorry, I do not understand this part. Are you talking about `feature dimension = len(dict)+4`? 
I do not know if there were any equation can explain languages' relationship. I am merely talking about dict.txt decides en/decoder's embed_dim. It is decided by fairseq/data/dictionary.py.

For multilingual tasks, there are examples in fairseq/examples/multilingual and translation: https://github.com/pytorch/fairseq/tree/main/examples/translation#multilingual-translation .
In general, people use BPE for multilingual tasks, and will not use a joined dict. (it will be a dict of bytes' expressions)
I do not think a joined dict is useful than BPE. A joined vocab is just a "new language" born from multiple languages. 
If I had to propose one, some multilingual persons may prefer using a mixture of different languages rather than switching two languages, which means they are using this "new language"

**Comment by xiaohangguo** [comment]
Thank you for your letter

Do you mean that now people express themselves in several languages?

In addition, I have a new question in the next step. I want to ask you whether you know the relevant commands of 'checkpoint'

In the next step, "influence: evaluate the model with the following command"



>export CUDA_VISIBLE_DEVICES=0
>data=PATH_TO_DATA
>modelfile=PATH_TO_SAVE_MODEL
>ref_dir=PATH_TO_REFERENCE

# average last 5 checkpoints
>python scripts/average_checkpoints.py --inputs ${modelfile} --num-update-checkpoints 5 --output ${modelfile}/average-model.pt 

# generate translation
>python generate.py ${data} --path $modelfile/average-model.pt --batch-size 250 --beam 1 --left-pad-source False --remove-bpe > pred.out

>grep ^H pred.out | cut -f1,3- | cut -c3- | sort -k1n | cut -f2- > pred.translation
>multi-bleu.perl -lc ${ref_dir} < pred.translation

This is my command lines:
>python scripts/average_checkpoints.py --inputs ${modelfile} --num-update-checkpoints 5 --output ${modelfile}/average-model.pt 
>Namespace(checkpoint_upper_bound=None, inputs=['/media/hang/1ba83754-8a9c-4989-9cf0-48bf763358da/hang/model1'], last_file=None, num_epoch_checkpoints=None, num_update_checkpoints=5, output='/media/hang/1ba83754-8a9c-4989-9cf0-48bf763358da/hang/model1/average-model.pt')

When I made the first step, I reported the following errors：
>Traceback (most recent call last):
>  File "scripts/average_checkpoints.py", line 173, in <module>
>    main()
>  File "scripts/average_checkpoints.py", line 161, in main
>    last=last,
>  File "scripts/average_checkpoints.py", line 88, in last_n_checkpoints
>    "Found {} checkpoint files but need at least {}", len(entries), n
>Exception: ('Found {} checkpoint files but need at least {}', 0, 5)


There are five 'checkpoints' in my' model 'file. Theoretically, it can calculate the average value of five points, but I don't know why it can't run. I can't find relevant information on the Internet, which has bothered me all day, no matter I'm' num '_ update_ checkpoints=?’ No matter how much I fill in, it doesn't seem to work. Do you know why?

Finally, thank you again for your reply.

**Comment by gmryu** [comment]
You exaggerate it. I mean sometimes an expression is more suitable than words in their first languages. But this only stands in a small group (like they share the same interest, games etc.) 

About average_checkpoints.py, if you are new to python, I recommend you add a lot of `print( variable )` to show progress of the program.
Since you cloned the repository, you can edit `average_checkpoints.py` and add `print("inputs"+ str(getattr(args,"inputs")) )` at line 127.
Actually you do not need it because at line 126 it prints args and from that

> Namespace(checkpoint_upper_bound=None, inputs=['/media/...g/model1'], 

you notice that inputs only get one string. Back to line 105 you see "inputs" and its help says 'Input checkpoint file paths.'
This makes me guess the program requires like `--inputs model1/ck1.pt model1/ck2.pt ... model1/ck5.pt` not a directory `model1` alone.

Also, do you use any code editor? (like vscode). 
Well, for example, this vscode can tell you where methods/functions are defined, run python by click the run button and add breakpoints so you can ask the program to stop before the line you decide.  When it stops, you can check most of variables for their values. 
(Adding arguments is a little bit tricky though.) So it just my little advice if you are new to programming.

**Comment by xiaohangguo** [comment]
I run it directly on Ubuntu. After configuring the environment, I go step by step. Now there is only one last step. But this error occurred after I ran it. I use dual system. I have PyCharm, Jupyter Notekook, and VS on Windows.

Do you mean that I write a.py script to do this last step? I have written Python programs.

But as for this checkpoint, I ran the code for the first time and didn't know what it did or how to use it. I don't have a compiler like PyCharm on Ubuntu yet. I have to write the program on the command line, so I need to configure PyCharm first. I'll try later.
Checkpoint1, checkpoint2... checkpoint1, checkpoint2...


I copied the data and model files on the USB flash drive and put them on windows. Let me show you.

![1649153316(1)](https://user-images.githubusercontent.com/72799392/161731783-6ca4c1d9-c9eb-4abe-b475-d353303ecf90.jpg)
![1649153341(1)](https://user-images.githubusercontent.com/72799392/161731787-6621f824-f656-46f3-a5e7-5af5cbf5071f.jpg)

**Comment by xiaohangguo** [comment]
All right ,I find it
>#!/usr/bin/env python3


> import argparse
> import collections
> import torch
> import os
> import re
> 
> 
> def average_checkpoints(inputs):
>     """Loads checkpoints from inputs and returns a model with averaged weights.
> 
>     Args:
>       inputs: An iterable of string paths of checkpoints to load from.
> 
>     Returns:
>       A dict of string keys mapping to various values. The 'model' key
>       from the returned dict should correspond to an OrderedDict mapping
>       string parameter names to torch Tensors.
>     """
>     params_dict = collections.OrderedDict()
>     params_keys = None
>     new_state = None
>     num_models = len(inputs)
> 
>     for f in inputs:
>         state = torch.load(
>             f,
>             map_location=(
>                 lambda s, _: torch.serialization.default_restore_location(s, "cpu")
>             ),
>         )
>         # Copies over the settings from the first checkpoint
>         if new_state is None:
>             new_state = state
> 
>         model_params = state["model"]
> 
>         model_params_keys = list(model_params.keys())
>         if params_keys is None:
>             params_keys = model_params_keys
>         elif params_keys != model_params_keys:
>             raise KeyError(
>                 "For checkpoint {}, expected list of params: {}, "
>                 "but found: {}".format(f, params_keys, model_params_keys)
>             )
> 
>         for k in params_keys:
>             p = model_params[k]
>             if isinstance(p, torch.HalfTensor):
>                 p = p.float()
>             if k not in params_dict:
>                 params_dict[k] = p.clone()
>                 # NOTE: clone() is needed in case of p is a shared parameter
>             else:
>                 params_dict[k] += p
> 
>     averaged_params = collections.OrderedDict()
>     for k, v in params_dict.items():
>         averaged_params[k] = v
>         averaged_params[k].div_(num_models)
>     new_state["model"] = averaged_params
>     return new_state
> 
> 
> def last_n_checkpoints(paths, n, update_based, upper_bound=None, last=None):
>     assert len(paths) == 1
>     path = paths[0]
>     if update_based:
>         pt_regexp = re.compile(r"checkpoint_\d+_(\d+)\.pt")
>     else:
>         pt_regexp = re.compile(r"checkpoint(\d+)\.pt")
>     files = os.listdir(path)
> 
>     entries = []
>     for f in files:
>         m = pt_regexp.fullmatch(f)
>         if m is not None:
>             sort_key = int(m.group(1))
>             if upper_bound is None or sort_key <= upper_bound:
>                 entries.append((sort_key, m.group(0)))
>     if len(entries) < n:
>         raise Exception(
>             "Found {} checkpoint files but need at least {}", len(entries), n
>         )
>     # print(entries)
>     newnew_entries = []
>     if last is not None:
>         new_entries = sorted(entries)
>         for entry in new_entries:
>             if entry[1] <= last:
>                 newnew_entries.append(entry)
> 
>         if len(newnew_entries) > 5:
>             return [
>                 os.path.join(path, x[1])
>                 for x in sorted(newnew_entries, reverse=True)[:n]
>             ]
>         else:
>             return [os.path.join(path, x[1]) for x in sorted(entries, reverse=True)[:n]]
>     else:
>         return [os.path.join(path, x[1]) for x in sorted(entries, reverse=True)[:n]]
> 
> 
> def main():
>     parser = argparse.ArgumentParser(
>         description="Tool to average the params of input checkpoints to "
>         "produce a new checkpoint",
>     )
>     # fmt: off
>     parser.add_argument('--inputs', required=True, nargs='+',
>                         help='Input checkpoint file paths.')
>     parser.add_argument('--last_file',
>                         help='last checkpoint.')
>     parser.add_argument('--output', required=True, metavar='FILE',
>                         help='Write the new checkpoint containing the averaged weights to this path.')
>     num_group = parser.add_mutually_exclusive_group()
>     num_group.add_argument('--num-epoch-checkpoints', type=int,
>                            help='if set, will try to find checkpoints with names checkpoint_xx.pt in the path specified by input, '
>                            'and average last this many of them.')
>     num_group.add_argument('--num-update-checkpoints', type=int,
>                            help='if set, will try to find checkpoints with names checkpoint_ee_xx.pt in the path specified by input, '
>                            'and average last this many of them.')
>     parser.add_argument('--checkpoint-upper-bound', type=int,
>                         help='when using --num-epoch-checkpoints, this will set an upper bound on which checkpoint to use, '
>                         'e.g., with --num-epoch-checkpoints=10 --checkpoint-upper-bound=50, checkpoints 41-50 would be averaged.')
>     # fmt: on
>     args = parser.parse_args()
>     print(args)
> 
>     num = None
>     is_update_based = False
>     if args.num_update_checkpoints is not None:
>         num = args.num_update_checkpoints
>         is_update_based = True
>     elif args.num_epoch_checkpoints is not None:
>         num = args.num_epoch_checkpoints
> 
>     assert (
>         args.checkpoint_upper_bound is None or args.num_epoch_checkpoints is not None
>     ), "--checkpoint-upper-bound requires --num-epoch-checkpoints"
>     assert (
>         args.num_epoch_checkpoints is None or args.num_update_checkpoints is None
>     ), "Cannot combine --num-epoch-checkpoints and --num-update-checkpoints"
> 
>     if args.last_file is not None:
>         last = args.last_file
>         last = last.split("/")[-1]
>     else:
>         last = None
>     if num is not None:
>         args.inputs = last_n_checkpoints(
>             args.inputs,
>             num,
>             is_update_based,
>             upper_bound=args.checkpoint_upper_bound,
>             last=last,
>         )
>         print("averaging checkpoints: ", args.inputs)
>     print("11111111")
>     new_state = average_checkpoints(args.inputs)
>     print("22222222")
>     torch.save(new_state, args.output)
>     print("33333333")
>     print("Finished writing averaged checkpoint to {}.".format(args.output))
> 
> 
> if __name__ == "__main__":
>     main()

**Comment by gmryu** [comment]
I forgot you ran code on ubuntsu part. My apology.
- For commandline tools you do not know how to use, you can try add `--help` or `-h` and feel lucky.
In this case, run `python scripts/average_checkpoints.py --help`.   It might tell you something.
(it will be a little hard to read)

- Also you do not have to write new python programs. 
If you want to get familiar with new tools/programs, while the best way is to read its readme and other's explanation, the second is to add print in the code. 


- I never used this and sorry I won't try it in any time. But I guess you can run it like:
`python scripts/average_checkpoints.py --inputs ${modelfile}  --num-epoch-checkpoints 5 --output ${modelfile}/average-model.pt`

The point is num-**epoch**-checkpoints and rename checkpointX.pt to **checkpoint_X.pt** because from its `--help` it says:

> --num-epoch-checkpoints'   'if set, will try to find checkpoints with names checkpoint_xx.pt in the '
>                            'path specified by input, and average last this many of them.')
> --num-update-checkpoints' 'if set, will try to find checkpoints with names checkpoint_ee_xx.pt in the path specified by'
>                            ' input, and average last this many of them.')

**Comment by xiaohangguo** [comment]
jaja,all right,It is nothing.No apologize.

- i see it before you send to me. Thanks. you are right. I'm lucky that using this command ,and lucky to learn from you. Thank u very very much.
- yes,I will do it.
- U are right!! I got it!

```
python scripts/average_checkpoints.py --inputs ${modelfile} --num-epoch-checkpoints 5 --output ${modelfile}/average-model.pt
Namespace(checkpoint_upper_bound=None, inputs=['/media/hang/1ba83754-8a9c-4989-9cf0-48bf763358da/hang/model'], last_file=None, num_epoch_checkpoints=5, num_update_checkpoints=None, output='/media/hang/1ba83754-8a9c-4989-9cf0-48bf763358da/hang/model/average-model.pt')
averaging checkpoints:  ['/media/hang/1ba83754-8a9c-4989-9cf0-48bf763358da/hang/model/checkpoint5.pt', '/media/hang/1ba83754-8a9c-4989-9cf0-48bf763358da/hang/model/checkpoint4.pt', '/media/hang/1ba83754-8a9c-4989-9cf0-48bf763358da/hang/model/checkpoint3.pt', '/media/hang/1ba83754-8a9c-4989-9cf0-48bf763358da/hang/model/checkpoint2.pt', '/media/hang/1ba83754-8a9c-4989-9cf0-48bf763358da/hang/model/checkpoint1.pt']
11111111

22222222
33333333

```

**Comment by xiaohangguo** [comment]
Thank you   very very very very very very very very  much!!!!!!!!!!!!!!!!!!
 Finally, i will calculate the bleu.


I finished.

```
perl multi-bleu.perl -lc ${ref_dir} < pred.translation
BLEU = 16.02, 55.71/26.21/14.00/7.77/4.42/2.52/1.46/0.87/0.54/0.34 (BP=0.802, ratio=0.820, hyp_len=45700, ref_len=55758)
It is not advisable to publish scores from multi-bleu.perl.  The scores depend on your tokenizer, which is unlikely to be reproducible from your paper or consistent across research groups.  Instead you should detokenize then use mteval-v14.pl, which has a standard tokenization.  Scores from multi-bleu.perl can still be used for internal purposes when you have a consistent tokenizer.

```

Thank u ,friend.
