### ISSUE TITLE
RuntimeError in fairseq-train

### ISSUE THREAD

**Issue by LeonKennedy** [facebookresearch/fairseq#4326]
## 🐛 Bug

just run fairseq-train

### To Reproduce

1. conda create -n fair python=3.7.13
2. pip3 install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cu112
3. cd fairseq
4. pip install --editable ./
5. fairseq-train 
see error:

Traceback (most recent call last):
  File "/home/hello/anaconda3/envs/fair/bin/fairseq-train", line 33, in <module>
    sys.exit(load_entry_point('fairseq', 'console_scripts', 'fairseq-train')())
  File "/mnt/data4t/code/fairseq/fairseq_cli/train.py", line 542, in cli_main
    args = options.parse_args_and_arch(parser, modify_parser=modify_parser)
  File "/mnt/data4t/code/fairseq/fairseq/options.py", line 153, in parse_args_and_arch
    raise RuntimeError()
RuntimeError

### Environment

 - fairseq Version : main
 - PyTorch Version 1.11
 - OS (e.g., Linux): ubauntu20.04
 - How you installed fairseq (`pip`, source): pip
 - Build command you used (if compiling from source):
 - Python version: 
 - CUDA/cuDNN version: 

### Additional context

i not found fairseq command in /home/hello/anaconda3/envs/fair/bin/

>> ls /home/hello/anaconda3/envs/fair/bin/
fairseq-eval-lm  fairseq-generate  fairseq-hydra-train  fairseq-interactive  fairseq-preprocess  fairseq-score  fairseq-train  fairseq-validate

>> python -c "import fairseq;print(fairseq.__version__)"
1.0.0a0+06c65c8

did i miss some step?

**Comment by gmryu** [comment]
You need to pass arguments to fairseq-train, like `fairseq-train data-bin/iwslt14.tokenized.de-en --optimizer adam --adam-betas '(0.9, 0.98)' --batch-size 1 ...`
Try some official examples: https://github.com/pytorch/fairseq/tree/main/examples/translation#training-a-new-model

By the way, where did you get pytorch for cu112, it does not exist in the official pytorch and link:https://download.pytorch.org/whl/cu112 shows nothing.

**Comment by tsingfa** [comment]
I met the same problem, and I think the essence of the problem is that Ubuntu and Win don't compile (guess?). However, it can be guaranteed that the program code itself is correct. I guess it should be a problem of compilation, because I send it to Linux after graphical editing in Windows, and it will report an error. However, if the original file is directly transmitted (it cannot be edited by Windows), It will work normally...

**Comment by gwenzek** [comment]
please use python 3.8 and use `fairseq-train --help` to get some help on how to use it
