### ISSUE TITLE
[data2vec] different config between released model[cfg] and default config

### ISSUE THREAD

**Issue by ddlBoJack** [facebookresearch/fairseq#4342]
Hi, I am trying to reproduce data2vec on speech.

I found that the config of the released model you provided is inconsistent with what is stated in the documentation. And some fields are not declared in the code, such as "diversity_weight". So can you please provide a new config or update the code?

And I found that you set `ema_layers_only: false` in the released model, which means you do ema for the whole transformer including position encoding. Is this setting a better one than the paper claims (share the position encoding)?

Many Thanks!

@alexeib

**Comment by FlorentMeyer** [comment]
Hi,

I can't find the "diversity_weight" that you are talking about anywhere in the `fairseq` codebase. 

Also, may I ask where you find this parameterization of `ema_layers_only: false`? Both in [Data2VecAudioConfig](https://github.com/pytorch/fairseq/blob/edb25c6b08c0631184b50f0c9cc7c5cb7ff01ef4/examples/data2vec/models/data2vec_audio.py#L71-L72) and in [`base_librispeech.yaml`](https://github.com/pytorch/fairseq/blob/edb25c6b08c0631184b50f0c9cc7c5cb7ff01ef4/examples/data2vec/config/audio/pretraining/base_librispeech.yaml#L80) it is set to `true` (and it is not overriden by the CLI in the [`readme`](https://github.com/pytorch/fairseq/tree/main/examples/data2vec) either).

**Comment by alexeib** [comment]
hi, the model that has been released was trained in a separate branch with a bunch of experimental settings that have not been released. we updated the model config so it can be loaded by the released code. please use the official yaml config files to repro the results - you should get very close to what the released model obtains.

**Comment by ddlBoJack** [comment]
Got it. Thanks!
