### ISSUE TITLE
fairseq-generate generates the sentences has a lot of duplications

### ISSUE THREAD

**Issue by yuanbinhuan** [facebookresearch/fairseq#4374]
### To Reproduce

Steps to reproduce the behavior (**always include the command you ran**):

1. Run cmd '....'
2. See error

### Environment

 - fairseq Version (e.g., 1.0 or main):
 - PyTorch Version (e.g., 1.0)
 - OS (e.g., Linux):
 - How you installed fairseq (`pip`, source):
 - Build command you used (if compiling from source):
 - Python version:
 - CUDA/cuDNN version:
 - GPU models and configuration:
 - Any other relevant information:

**Comment by sarapapi** [comment]
@yuanbinhuan How have you solved this problem? I see the same phenomenon In my outputs
