### ISSUE TITLE
how to use the scripts in wav2vec repository to generate manifest files .ltr for LibriSpeech.

### ISSUE THREAD

**Issue by guobabaya** [facebookresearch/fairseq#4414]
Prepare manifest of the dataset
Use the scripts in wav2vec repository to generate manifest files (.tsv and .ltr) for LibriSpeech. The manifest of other datasets follows the similar format as that of the Librispeech. The .tsv file contains one extra column for class labels

<root directory>
<relative path> <number of frames of the audio> <class label>
<relative path> <number of frames of the audio> <class label>

The .ltr file contains columns for class labels, prompts and transcriptions

<class label> <prompt> <transcription>
<class label> <prompt> <transcription>

i use manifest.py of wav2vec to generate train.tsv,but i don't konw how to generate files about .ltr.

**Comment by noitanec** [comment]
https://github.com/facebookresearch/fairseq/blob/main/examples/wav2vec/README.md#prepare-training-data-manifest
`
python examples/wav2vec/wav2vec_manifest.py /path/to/waves --dest /manifest/path --ext $ext --valid-percent $valid
`

**Comment by guobabaya** [comment]
> https://github.com/facebookresearch/fairseq/blob/main/examples/wav2vec/README.md#prepare-training-data-manifest `python examples/wav2vec/wav2vec_manifest.py /path/to/waves --dest /manifest/path --ext $ext --valid-percent $valid`

thank you ，i already finished it.

**Comment by srksaurabh1** [comment]
hey how did you do it, I am stuck at this.
