### ISSUE TITLE
Module Not Found Error

### ISSUE THREAD

**Issue by jayachandrakalakutagar** [facebookresearch/fairseq#4429]
## 🐛 Bug
was trying to run inference on pre-trained transformer TTS model downloaded from[ here](https://dl.fbaipublicfiles.com/fairseq/s2/vctk_transformer_phn.tar)
No module named 'fairseq'
Help me out to fix the bug
![issue](https://user-images.githubusercontent.com/96902361/169467171-d768b581-766b-45bd-96b0-4ad7741bd20b.png)

**Comment by gmryu** [comment]
Have you installed fairseq?

**Comment by jayachandrakalakutagar** [comment]
got my mistake
