### ISSUE TITLE
Whats the difference between task `translation_multi_simple_epoch` and `multilingual_translation`.

### ISSUE THREAD

**Issue by BrightXiaoHan** [facebookresearch/fairseq#4433]
#### What is your question?
Whats the difference between task `translation_multi_simple_epoch` and `multilingual_translation`.

#### What have you tried?
I want to train a multilingual model. In the examples, I found two defferent tasks. The first is  from https://github.com/facebookresearch/fairseq/tree/main/examples/translation#multilingual-translation, and the other is from 
https://github.com/facebookresearch/fairseq/blob/main/examples/multilingual/README.md#training

What's the different between them. How to choose between them.

#### What's your environment?

 - fairseq Version (e.g., 1.0 or main): main
 - PyTorch Version (e.g., 1.0): 1.10
 - OS (e.g., Linux): centos 7
 - How you installed fairseq (`pip`, source): source
 - Build command you used (if compiling from source):
 - Python version: 3.8
 - CUDA/cuDNN version: 11.6
 - GPU models and configuration: 
 - Any other relevant information:

**Comment by ahmadshapiro** [comment]
@BrightXiaoHan  did you find an answer to your question ?

**Comment by BrightXiaoHan** [comment]
Hi @ahmadshapiro. I think task "multilingual_translation" is a more general task. It can use different encoders and decoders for different languages and you can also choose to share all parameters.  But "translation_multi_simple_epoch" task use prefix tags to distinguish different language. This means that it shares all parameters by default and cannot be routed to different encoder decoders according to different languages. MBart is trained by "translation_multi_simple_epoch" task.
