### ISSUE TITLE
Can I do translation without generator using the vanilla transformer?

### ISSUE THREAD

**Issue by KevinZhoutianyi** [facebookresearch/fairseq#4444]
Hi!

I've read the source code for machine translation and it seems that we need to specify the data to create a generator. And that generator will take the model and the sentences to help us do the [translation](https://github.com/facebookresearch/fairseq/blob/e0884db9a7ce83670e21af39bf785b616ce5e3e3/examples/attention_head_selection/src/speech_to_text_head_selection.py#L178). 

However, I need to do the translation more frequently in the coding (its an end2end self teaching project, so I need to do translation during training). Therefore, is there any way to make my own trained model translate sentences easily? 
like this:
```
output_ids = model.generate( input_ids = input_ids, num_beams = num_beams, early_stopping = True, max_length = max_length, length_penalty =0.6, repetition_penalty = 1 )
```
where the input_ids are the tokenized source sentences.

Any help would be appreciated!

**Comment by gmryu** [comment]
I do not get your complain about generator. Are you complaining about how to provide user inputs to model?
Following codes are one of my generate method.

```
def generate(sample,fqmodel,cfg,generator,task=None,prefix_tokens=None,constraints=None):
    '''
    !NOTE: every fairseq Task has def inference_step(...), and this is a copy with a little adjustment.

    a fairseq SequenceGenerator will take a dict with "net_input" as a batch input.
    dict["net_input"] will be given to model's forward.

    Args:
        sample: one batch of data. will be passed to model at once so too big size may cause out of memeory.
        fqmodel: fairseq model that works with generator
        cfg: whole cfg. used for fqmodel.prepare_for_inference_(cfg), which may improve generation speed.
        generator: If None, then =task.build_generator([fqmodel],cfg.generation)
        task: only when generator==None, build one from this task.

        prefix_tokens: (torch.LongTensor, optional): force decoder to begin with these tokens.
        constraints (torch.LongTensor, optional): force decoder to include the list of constraints
        bos_token (int, optional): beginning of sentence token (default: self.eos)
        
    Returns:
        a list of sample size list inside. Then each list has num_beams dicts of fairseq's generate output.
        It has "tokens":tensor, "score":float, "attention":tensor, "alignment":tensor, "positional_scores":tensor.
            Use backToString(tokens tensor,...) to convert them into actual words.
    '''
    fqmodel.prepare_for_inference_(cfg)
    if(generator is None):
        generator=task.build_generator([fqmodel], cfg.generation)
    with torch.no_grad():
        return generator.generate( [fqmodel], sample, prefix_tokens=prefix_tokens, constraints=constraints )


def backToString(tokens, taskDictionary,bpe_symbol=None,
    escape_unk=False, extra_symbols_to_ignore=None,
    unk_string=None,include_eos=False,separator=" ",):
    '''
   use this to make ids back to normal chars/words.
    Args:
        tokens:  tensors
        taskDictionary:(fairseq.data.Dictionary) give the correct dictionary, like task.source_dictionary
    Return:
        a list of decoded data according to encoded 
    '''
    return taskDictionary.string(tokens, bpe_symbol=bpe_symbol,escape_unk=escape_unk,\
            extra_symbols_to_ignore=extra_symbols_to_ignore,unk_string=unk_string,include_eos=include_eos,separator=separator)
```

cfg can be obtained if you load a fairseq checkpoint. Or you can create one.
The best official example is to read fairseq/fairseq_cli/interactive.py, which tells you how to handle user inputs.

**Comment by KevinZhoutianyi** [comment]
Hi gmryu,
Thanks for your code and explanation!
My project is a bit special, it's like, for each iteration, model A generate a sentence and then model B learn from that generated sentences. Model A and B will both be updated for each iteration. That's why I said I need to call the generate function more frequently.
In that case, I guess, I can just create ```generator=task.build_generator([fqmodel], cfg.generation)``` at the beginning and use ```generator.generate``` for each batch
