### ISSUE TITLE
Can't download preprocessed WMT'16 En-De data provided by Google at fairseq/examples/scaling_nmt/

### ISSUE THREAD

**Issue by 1ucky40nc3** [facebookresearch/fairseq#4454]
#### How can I download the preprocessed dataset?
I can't download the  preprocessed WMT'16 En-De data provided by Google at `fairseq/examples/scaling_nmt/`. The provided [link](https://drive.google.com/uc?export=download&id=0B_bZck-ksdkpM25jRUN2X2UxMm8) seems to be broken. Can you provide a new link? Are there any other ways to get the data?

Here is the raw snippet of the [README.md](https://github.com/facebookresearch/fairseq/blob/main/examples/scaling_nmt/README.md)
```
## Training a new model on WMT'16 En-De

First download the [preprocessed WMT'16 En-De data provided by Google](https://drive.google.com/uc?export=download&id=0B_bZck-ksdkpM25jRUN2X2UxMm8).
```

**Comment by neilwen987** [comment]
Have you solved this problem?

**Comment by jychen01** [comment]
> Have you solved this problem?

I met the same problem. Have you solved it?

**Comment by nathanielhobbs** [comment]
For others who have run into this issue, you can generate the dataset yourself using the script provided by Google:

https://github.com/google/seq2seq/blob/master/bin/data/wmt16_en_de.sh
