### ISSUE TITLE
Why is the translation of long texts limited to a few initial sentences?

### ISSUE THREAD

**Issue by molokanov50** [facebookresearch/fairseq#4470]
Hi team,

I'm just trying to translate (EN-RU) long texts consisting of 6 - 8 sentences but not exceeding 100 tokens in general (in order to not overcome model's memory consumption) using Fairseq's pretrained models (m2m, mBart, etc.). My input file is composed of every such text per line. According to the recommended workflow, I initially perform spm_encode.py, then binarization with fairseq-preprocess, and then translation with fairseq-generate. But in my output, I typically see no more than 3 - 4 translated sentences from the beginning of every text. Why does this occur? 
Meanwhile, in several papers, there is a scattered info that only one sentence per line is recommended in input files at all, but there is no clear explanation of it.

**Comment by erip** [comment]
When you say "100 tokens", do you mean 100 tokens (~words) or 100 subword tokens? 100 "words" can easily surpass the 256 subword token max and then the documents might get truncated.

**Comment by molokanov50** [comment]
I meant regular words but now I verified that my **spm-encoded** text has 144 subword tokens - of course, if only whitespaces separate subword tokens from each other. Besides I have there 100 'long underscores' which represent whitespaces of the **source** text. Even if long underscores are regarded as independent subword tokens (BTW are they?), I have in total 244 subword tokens. That should satisfy the network's limits. The truncation occurs after the 121st whitespace of the **spm-encoded** text. Until this position, 84 long underscores are encountered. And there is a sentence boundary at this position.
Is there maybe any config in which I can specify the upper limit of subword tokens to translate?
Any other workarounds?

**Comment by erip** [comment]
In general you have `len(spm_encoded_line.strip().split())` subwords for a given `spm_encoded_line`. When you train a model you specify `--max-source-positions` which defines the maximum source sequence length handleable by your model. Check what this is for your model.

**Comment by molokanov50** [comment]
@erip 
Until now I performed tests only on **pretrained** models available in fairseq examples. There is no change in my result if I vary my `--max-source-positions` option. For all my input sentences, the truncation always takes place around 110th-125th subwords exactly at the sentence boundary, and the boundary of the next sentence is already further than 135th subword.
Looks like there is a default input length set up to ~128 subwords.
Should I re-train my model with a different `--max-source-positions` value to have an opportunity to translate longer input sequences?

**Comment by erip** [comment]
Suboptimally you could feed smaller chunks in and recombine in post-processing.

**Comment by molokanov50** [comment]
Can be closed, thanks.
