### ISSUE TITLE
'TranslationFromPretrainedBARTTask' object has no attribute 'args' under fairseq version 0.12.0

### ISSUE THREAD

**Issue by tianshuailu** [facebookresearch/fairseq#4479]
### To Reproduce

Steps to reproduce the behavior (**always include the command you ran**):

1. Run the following command

PRETRAIN=mbart.cc25 # fix if you moved the downloaded checkpoint
langs=ar_AR,cs_CZ,de_DE,en_XX,es_XX,et_EE,fi_FI,fr_XX,gu_IN,hi_IN,it_IT,ja_XX,kk_KZ,ko_KR,lt_LT,lv_LV,my_MM,ne_NP,nl_XX,ro_RO,ru_RU,si_LK,tr_TR,vi_VN,zh_CN

fairseq-train path_2_data \
  --encoder-normalize-before --decoder-normalize-before \
  --arch mbart_large --layernorm-embedding \
  --task translation_from_pretrained_bart \
  --source-lang hi_IN --target-lang en_XX \
  --criterion label_smoothed_cross_entropy --label-smoothing 0.2 \
  --optimizer adam --adam-eps 1e-06 --adam-betas '(0.9, 0.98)' \
  --lr-scheduler polynomial_decay --lr 3e-05 --warmup-updates 2500 --total-num-update 40000 \
  --dropout 0.3 --attention-dropout 0.1 --weight-decay 0.0 \
  --max-tokens 1024 --update-freq 2 \
  --save-interval 1 --save-interval-updates 5000 --keep-interval-updates 10 --no-epoch-checkpoints \
  --seed 222 --log-format simple --log-interval 2 \
  --restore-file $PRETRAIN \
  --reset-optimizer --reset-meters --reset-dataloader --reset-lr-scheduler \
  --langs $langs \
  --ddp-backend legacy_ddp

2. Got the following error

Traceback (most recent call last):
  File "/usr/local/bin/fairseq-train", line 8, in <module>
    sys.exit(cli_main())
  File "/usr/local/lib/python3.7/dist-packages/fairseq_cli/train.py", line 557, in cli_main
    distributed_utils.call_main(cfg, main)
  File "/usr/local/lib/python3.7/dist-packages/fairseq/distributed/utils.py", line 369, in call_main
    main(cfg, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/fairseq_cli/train.py", line 133, in main
    task.load_dataset(valid_sub_split, combine=False, epoch=1)
  File "/usr/local/lib/python3.7/dist-packages/fairseq/tasks/translation_from_pretrained_bart.py", line 66, in load_dataset
    paths = utils.split_paths(self.args.data)
AttributeError: 'TranslationFromPretrainedBARTTask' object has no attribute 'args'

### Expected behavior
After running the above code, it should start training the model, which still works earlier today with fairseq version 0.10.2, but it seems that fairseq just got an update to 0.12.0 and now the code gives an error.

### Environment

 - fairseq Version 0.12.0:

**Comment by gmryu** [comment]
Yes, TranslationTask uses `self.cfg` instead of `self.args` now.

And the quicker fix is to do it yourself and upload it, so enjoy it.
A replace all `self.args` to `self.cfg` will do.

**Comment by tianshuailu** [comment]
Hi gmryu,

Thank you so much for the reply, could you explain a bit more about how to fix and upload it myself? I'm just using the command `!pip install fairseq` when I use fairseq.

**Comment by gmryu** [comment]
Wait, are you using google colab or something remote?
If you are installing with `pip` you have to find where those installed package are.
Use `which fairseq-train` or `where fairseq-train` may tell you where environment is and you go there( or one up) and find folders like `lib/site-packages/python3.10/fairseq`

Once you found the fairseq folder, open `fairseq/tasks/translation_from_pretrained_bart.py` and use your editor to replace all.
(You can use `vim` if it is on linux or use python to do this for you)
Then test it whether it works or not.

(I know nothing about upload or sending pull request. But I guess it is not a fairseq issue, more like how to work with public library. Would be nice if you teach me in the future.)

--

No matter where you run the programs, I believe the best install option is 
`git clone https://github.com/pytorch/fairseq`  this will download fairseq repository into current directory and
`cd fairseq` open it
`pip install --editable ./` this will install your local fairseq. 
If you want to upgrade, `cd fairseq` and `git pull` which will update till the main branch.
This applies to most (famous) packages found on github

**Comment by tianshuailu** [comment]
Thank you so much for your help. I found the older version on the branch that works for the model. And I installed it with `--editable` as you suggested. Now it works :)
