### ISSUE TITLE
Trying to debug pre-trained "Textless S2ST on real data" (mHuBERT) model

### ISSUE THREAD

**Issue by liamdugan** [facebookresearch/fairseq#4489]
#### What is your question?
I'm following the instructions from https://github.com/facebookresearch/fairseq/blob/main/examples/speech_to_speech/docs/textless_s2st_real_data.md to setup the pre-trained mHuBERT model. I want to encode an english audio wav file and decode it in another language but I'm getting a pretty weird error and I'd like some help debugging.

#### Code
 I'm running this command to encode the english waveform
```
python examples/speech_recognition/new/infer.py \
    --config-dir examples/hubert/config/decode/ \
    --config-name infer_viterbi \
    task.data=/content/data \
    task.normalize=false \
    common_eval.results_path=/content/results/log \
    common_eval.path=/content/data/mhubert_base_vp_en_es_fr_it3.pt \
    dataset.gen_subset=liam-speech \
    '+task.labels=["unit"]' \
    +decoding.results_path=/content/results \
    common_eval.post_process=none \
    +dataset.batch_size=1 \
    common_eval.quiet=True
```

and I get this error
```
Traceback (most recent call last):
  File "examples/speech_recognition/new/infer.py", line 436, in hydra_main
    distributed_utils.call_main(cfg, main)
  File "/usr/local/lib/python3.7/dist-packages/fairseq/distributed/utils.py", line 369, in call_main
    main(cfg, **kwargs)
  File "examples/speech_recognition/new/infer.py", line 385, in main
    processor.process_sample(sample)
  File "examples/speech_recognition/new/infer.py", line 308, in process_sample
    sample=sample,
  File "/usr/local/lib/python3.7/dist-packages/fairseq/tasks/fairseq_task.py", line 538, in inference_step
    models, sample, prefix_tokens=prefix_tokens, constraints=constraints
  File "/content/fairseq/examples/speech_recognition/new/decoders/base_decoder.py", line 37, in generate
    emissions = self.get_emissions(models, encoder_input)
  File "/content/fairseq/examples/speech_recognition/new/decoders/base_decoder.py", line 46, in get_emissions
    encoder_out = model(**encoder_input)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/fairseq/models/hubert/hubert.py", line 494, in forward
    proj_x_m_list = proj_x_m.chunk(len(target_list), dim=-1)
TypeError: object of type 'NoneType' has no len()
```

I think this is likely because I added an empty version of `dict.unit.txt` to my `DATA_DIR` folder. The instructions said to download the pretrained model and dictionary to the `DATA_DIR` folder but I couldn't find the dictionary and could only find the pretrained model (`mhubert_base_vp_en_es_fr_it3.pt`). Is the dictionary file for this model available anywhere? or am I correct to make a dummy `dict.unit.txt` file for the pre-trained model.

I also suspect that there might be an issue with the `prep_sn_data.py` script since the `.unit` file in my `DATA_DIR` only has a `0` and a newline character. I also had to manually process my audio file to have the correct sampling rate since the script didn't seem to be doing that. Not sure if that's expected behavior either. 

In any case, would really appreciate some help debugging here. Thanks!

#### What's your environment?
Google Colab
 - fairseq Version (e.g., 1.0 or main): main
 - PyTorch Version (e.g., 1.0): 1.11.0
 - OS (e.g., Linux): Linux
 - How you installed fairseq (`pip`, source): pip
 - Build command you used (if compiling from source):
 - Python version: 3.7.13
 - CUDA/cuDNN version: 11.3
 - GPU models and configuration: NVIDIA Tesla T4
 - Any other relevant information: Running on Google Colab

**Comment by liamdugan** [comment]
Closing issue, I realized that the file the instructions are referencing is the normalizer and not the pre-trained model

**Comment by dina-adel** [comment]
@liamdugan Hello, I am just wondering whether you were able to get an output using the provided instructions? I am trying the same model now, but I am getting a lot of errors.

**Comment by AhmedEssam19** [comment]
@liamdugan Did it work with you?
