### ISSUE TITLE
why use max_tokens in wav2vec 2.0? batch_size is not good?

### ISSUE THREAD

**Issue by YooSungHyun** [facebookresearch/fairseq#4503]
max_tokens is too confuse to use!

i want to batch_size, but many references use max_token

just, that is better than batch_size? then, why?

**Comment by gmryu** [comment]
Judging from mylotte's comment, max_token is not better or worse than batch_size in performance. It is chosen as personal preference.
https://github.com/facebookresearch/fairseq/issues/165
https://github.com/facebookresearch/fairseq/issues/37
So max_token provides a more stable control over training as well as memory usage.
