### ISSUE TITLE
How to generate back translation pairs with monolingual data

### ISSUE THREAD

**Issue by tianshuailu** [facebookresearch/fairseq#4537]
#### What is your question?
Hi, I'm trying to use fairseq-generate to get back-translation pairs with only monolingual data on a pretrained MBART model, but I couldn't find an example of how to do it in the documentation.  Here is the command I used, but it doesn't work.
`fairseq-generate ./output 
  --path ./model.pt 
  --gen-subset train 
  --batch-size 32 --beam 5`

I assume it is also required to preprocess the data first with fairseq-preprocess, this is the command I used
`fairseq-preprocess 
--trainpref ./mono.spm.ml 
--destdir ./output 
--workers 70 `
and this is the output
![image](https://user-images.githubusercontent.com/22446406/177346071-6fe564ad-e12a-46af-bc6a-81fbaac00ca0.png)

I'm not sure where went wrong, but I think probably both commands are not exactly correct :)

Any suggestion would be great, thx!

#### What's your environment?

 - fairseq Version v0.10.2:

**Comment by gmryu** [comment]
When doing the 2nd or latter `fairseq-preprocess` You have to specified `--srcdict {your first src dict.txt} --tgtdict {your first tgt dict.txt}`
So there will be a consistency between your different dataset for the same model.
A small thought, if it is monolingual, you can use `--joined-dictionary --source-lang {lang} --target-lang {lang}`

Also, what is not working?

**Comment by tianshuailu** [comment]
Hi @gmryu, thank you for your reply, I made some changes according to your reply, and now it works!
