### ISSUE TITLE
Where in Transformer Decoder is the first decoding step implemented?

### ISSUE THREAD

**Issue by st-vincent1** [facebookresearch/fairseq#4553]
#### What is your question?

I'm studying the code for the Transformer architecture in fairseq (`fairseq/fairseq/models/transformer/*`) and I'm trying to understand the decoding process during inference. I'm struggling to find where in code the batch of BOS tokens is first fed to the Decoder to begin decoding. 

#### What have you tried?
I've looked in `fairseq_decoder.py`, `transformer_decoder.py`, other files describing the architecture. I'm guessing the step-by-step decoding is happening somewhere else in the ecosystem (perhaps `search.py`?) but I could not find any links between the Transformer implementation and the searches. Could a more experienced person point me in the right direction? :)

#### What's your environment?
Python 3.10, latest fairseq (0.12.2), built with `pip install --editable ./` when in `fairseq/`.

**Comment by gmryu** [comment]
Assuming you are doing a normal translation task,
In `fairseq-train`, all decoder inputs is fed as net_input["prev_output_tokens"], which is created by dataset [LanguagePairDataset](https://github.com/facebookresearch/fairseq/blob/main/fairseq/data/language_pair_dataset.py#L81-L109).
It is almost the same as the target, except `move_eos_to_beginning=True`, so BOS is eos.
If you are using other task, dataset class, check those definition as well.

In `fairseq-generate` and `interactive`,  they both use [SequenceGenerator](https://github.com/facebookresearch/fairseq/blob/main/fairseq/sequence_generator.py) by default. Search `bos` you will find how they are used inside.
