### ISSUE TITLE
How to use optimizer of "--composite" in shell script?

### ISSUE THREAD

**Issue by zyhuang-USTC** [facebookresearch/fairseq#4563]
Hello, I try to set up a --composite config with different optimizer parameters in linux shell, how to set the args? I try a lot of formats, but it doesn't work.

#### Code
This is the shell script:

![image](https://user-images.githubusercontent.com/14012194/178269028-df636230-2cca-43b9-99ff-892e03a527c1.png)

This is the error:

![image](https://user-images.githubusercontent.com/14012194/178269168-bcf7514c-7d83-4abc-9d93-4bfb90dac715.png)

**Comment by gmryu** [comment]
I have not used this composite.
But when passing a dictionary, its format is `'{ 'key1' : value1, 'key2' : {'k1':v1}, 'key3': "(0,1)" }'`

Neither ' nor " can be changed.

----

By the way, how does composite determine which parameter using which optimizer.
That `discriminator` is whose parameter? Can you give one part of discriminator a different optimizer than other discriminator?

**Comment by zyhuang-USTC** [comment]
You can do like this, the --composite and --groups are used jointly:

      for p in self.net_g.parameters():
            p.param_group = "generator"

       for p in self.net_d.parameters():
            p.param_group = "discriminator"

**Comment by gmryu** [comment]
@zyhuang-USTC  Thanks.
Does that mean it can only be used with a customized model?

**Comment by zyhuang-USTC** [comment]
@gmryu Yes, there are few examples of this optimizer, only seen on wav2vec. So, I think this optimizer is generally used for custom models.

**Comment by zyhuang-USTC** [comment]
@alexeib Hi, do you know how to use this optimizer （--composite， --groups）？

**Comment by alexeib** [comment]
correct, you would have to modify the model to set groups as zyhuang-USTC showed above. I have only used it with hydra entry point which uses yaml configs. you can look at w2v unsupervised example here: https://github.com/facebookresearch/fairseq/blob/b5a039c292facba9c73f59ff34621ec131d82341/examples/wav2vec/unsupervised/config/gan/w2vu.yaml

**Comment by b3y0nd** [comment]
Has anyone solved the problem of using the composite parameter on the command line? @zyhuang-USTC
