### ISSUE TITLE
How can I extract features using multilingual pre-trained wav2vec models?

### ISSUE THREAD

**Issue by xjtupanda** [facebookresearch/fairseq#4585]
### Before asking:
1. search the issues.
2. search the docs.

#### What is your question?
I want to extract audio features using multilingual pre-trained wav2vec 2.0 (XLSR) models,  provided in the wav2vec README doc.[https://github.com/facebookresearch/fairseq/blob/main/examples/wav2vec/README.md](url)   But when I used the code also provided in the doc, I met some problems.
#### Code

```
$ PYTHONPATH=/path/to/fairseq python examples/wav2vec/wav2vec_featurize.py --input /path/to/task/waves --output /path/to/output \
--model /model/path/checkpoint_best.pt --split train valid test
```

#### What have you tried?
I have also tried using the code snippet to test.
```
import torch
import fairseq

cp = torch.load('/path/to/vq-wav2vec.pt')
model, cfg, task = fairseq.checkpoint_utils.load_model_ensemble_and_task([cp])
model = model[0]
model.eval()

wav_input_16khz = torch.randn(1,10000)
z = model.feature_extractor(wav_input_16khz)
```
I have tested with model :
Wav2Vec 2.0 Large (LV-60 + CV + SWBD + FSH) **  --> w2v_large_lv_fsh_swbd_cv.pt
XLSR-53 -->   xlsr_53_56k.pt 
Wav2Vec 2.0 Base --> wav2vec_small.pt

It seems like only the original pre-trained model "Wav2Vec 2.0 Base" without any finetuning works. And other models report errors:
```
omegaconf.errors.ConfigKeyError: Key 'eval_wer' not in 'AudioPretrainingConfig'
    full_key: eval_wer
    object_type=AudioPretrainingConfig

```
Now that I need a model supporting the language I need, which is only included in the CommonVoice dataset, I have no idea which model to use.

#### What's your environment?

 - fairseq Version (e.g., 1.0 or main):  main
 - PyTorch Version (e.g., 1.0):  1.12.0
 - OS (e.g., Linux):  Linux
 - How you installed fairseq (`pip`, source):  source
 - Build command you used (if compiling from source):  pip install --editable ./
 - Python version:  3.7.12
 - CUDA/cuDNN version:  10.2
 - GPU models and configuration: Nvidia Geforce RTX 2080Ti
 - Any other relevant information:

**Comment by xjtupanda** [comment]
Seems like there are some keys in the OmegaConf Dict missed in the pretraining config, so I consult the OmegaConf doc and drop those keys manually and I'm loading sucessfully now. Belows are the code for modifying the model checkpoint.
But I don't know if this would have any negative impact on inference results since I'm new in this area.

```
import torch
from omegaconf import DictConfig, open_dict

cp_path = './ckpt/xlsr_53_56k.pt'
cp = torch.load(cp_path)
wrong_key = ['eval_wer','eval_wer_config', 'eval_wer_tokenizer', 'eval_wer_post_process', 'autoregressive']
cfg = DictConfig(cp['cfg'])
with open_dict(cfg):
    for k in wrong_key:
        cfg.task.pop(k)
cp['cfg'] = cfg
torch.save(cp, './ckpt/xlsr_53_56k_new.pt')
```

**Comment by avsaipavan** [comment]
I have used your key dropping code to modify the xlsr_53_56k checkpoint. However, I am now stuck with this error:

assert self.key_type is None or isinstance(self.key_type, type)
AssertionError

@xjtupanda Were you also encountering the same issue when finetuning xlsr_53_56k pre-trained model (modified checkpoint) from fairseq? If so, how did you solve this error?

**Comment by jenying1107** [comment]
> Seems like there are some keys in the OmegaConf Dict missed in the pretraining config, so I consult the OmegaConf doc and drop those keys manually and I'm loading sucessfully now. Belows are the code for modifying the model checkpoint. But I don't know if this would have any negative impact on inference results since I'm new in this area.
> 
> ```
> import torch
> from omegaconf import DictConfig, open_dict
> 
> cp_path = './ckpt/xlsr_53_56k.pt'
> cp = torch.load(cp_path)
> wrong_key = ['eval_wer','eval_wer_config', 'eval_wer_tokenizer', 'eval_wer_post_process', 'autoregressive']
> cfg = DictConfig(cp['cfg'])
> with open_dict(cfg):
>     for k in wrong_key:
>         cfg.task.pop(k)
> cp['cfg'] = cfg
> torch.save(cp, './ckpt/xlsr_53_56k_new.pt')
> ```

I fixed the problem by this method, thank you!

**Comment by QianYuuRiri** [comment]
Extremely helpful！
