### ISSUE TITLE
How to use the NLLB Language identification .bin model?

### ISSUE THREAD

**Issue by ArturPrzybysz** [facebookresearch/fairseq#4592]
Hi! Thank you for your great work and making it publicly available! 

I am trying to use your NLLB model and thanks to the huggingface integration it is easy to do.
However, you have also published the LID model's .bin file and I am struggling to use it.

Can you provide a simple example of its usage?
What is the .bin file?

**Comment by Celebio** [comment]
hi @ArturPrzybysz ,
you can use the model using [fastText](https://fasttext.cc/).

A simple command looks like this:
`./fasttext predict-prob lid218e.bin mytestfile.txt`
where `mytestfile.txt` contains one sentence per line to be predicted.

More information on how to use fastText available [here](https://fasttext.cc/docs/en/supervised-tutorial.html).

Regards,
Onur

**Comment by ArturPrzybysz** [comment]
@Celebio 
Thank you for the help!
I managed to make it work in code thanks to you.

**Comment by Jourdelune** [comment]
Hello, can you indicate where you found the identification model (lid218e.bin)? After some research I did not find it.
Have a nice day!

**Comment by baiziyuandyufei** [comment]
where is the lid218e.bin？

**Comment by ArturPrzybysz** [comment]
@baiziyuandyufei 
It's here: [https://github.com/facebookresearch/fairseq/tree/nllb#lid-model](https://github.com/facebookresearch/fairseq/tree/nllb#lid-model)

**Comment by fatihbeyhan** [comment]
Hi,

I suppose this is the language identification model which was used in NLLB paper. Can you please tell me where is the fasttext checkpoint (.bin) for this LID model? This link seems to not take you anywhere: https://github.com/facebookresearch/fairseq/tree/nllb#lid-model
