### ISSUE TITLE
Where is the list with all the possible languages?

### ISSUE THREAD

**Issue by lena-kru** [facebookresearch/fairseq#4636]
I need to translate texts with a lot of different languages.
I have found some language's names at documentation, however not all.

Where can I get the full list of possible languages like `rus_Cyrl` and `eng_Latn`?
Or is it possible to detect the `src_lang` inside the model?

**Comment by gmryu** [comment]
You can load a fairseq checkpoint and see what is inside.
Says:
```
from fairseq.checkpoint_utils import load_checkpoint_to_cpu

all_state=load_checkpoint_to_cpu("{path_to_the_checkpoint.pt}")
cfgargs=all_state["cfg"]
mdlargs=cfgargs["model"].__dict__
print(mdlargs["source_lang"])
```
