### ISSUE TITLE
fairseq-train: error: argument --max-tokens: invalid Optional value: '512'

### ISSUE THREAD

**Issue by tianshuailu** [facebookresearch/fairseq#4649]
## ❓ Questions and Help

When I tried to train the model with the following command, I kept getting this error, from another issue https://github.com/facebookresearch/fairseq/issues/4032#issuecomment-977613382, someone solved it by downgrading python to 3.7, but rn I couldn't downgrade my python, so is there a way to get around it?

command
`fairseq-train  /srv/scratch4/naepli/ltian/NMTAdapt   --encoder-normalize-before --decoder-normalize-before   --arch mbart_large --layernorm-embedding   \
--task translation_multi_simple_epoch    --criterion label_smoothed_cross_entropy --label-smoothing 0.2   --optimizer adam --adam-eps 1e-06 --adam-betas '(0.9, 0.98)' \
--lr-scheduler polynomial_decay --lr 3e-05 --min-lr -1 --warmup-updates 50 --total-num-update 80000   --dropout 0.3 --attention-dropout 0.1 --weight-decay 0.0 \
--max-tokens 512 --update-freq 8   --save-interval 1 --save-interval-updates 7000 --keep-interval-updates 10 --no-epoch-checkpoints   --seed 222 --log-format simple \
--log-interval 2  --save-dir /srv/scratch4/naepli/ltian/train_nmt \
--restore-file /srv/scratch4/naepli/ltian/pretrained_model.pt  --reset-optimizer --reset-meters --reset-dataloader --reset-lr-scheduler   \
--ddp-backend no_c10d  --max-epoch 128  --skip-invalid-size-inputs-valid-test --fp16 \
--langs ar_AR,cs_CZ,de_DE,en_XX,es_XX,et_EE,fi_FI,fr_XX,gu_IN,hi_IN,it_IT,ja_XX,kk_KZ,ko_KR,lt_LT,lv_LV,my_MM,ne_NP,nl_XX,ro_RO,ru_RU,si_LK,ml_XX,no_ML,no_HI \
--lang-pairs en_XX-hi_IN,en_XX-ml_XX,no_HI-hi_IN,no_ML-ml_XX  --virtual-epoch-size 1388932 --virtual-data-size 138893200 \
--sampling-weights "{'main:en_XX-hi_IN': 1,'main:en_XX-ml_XX': 1,'main:no_HI-hi_IN': 1,'main:no_ML-ml_XX':1}" --keep-inference-langtok --encoder-langtok src \
--decoder-langtok --lang-tok-style mbart --checkpoint-suffix pt`

error mesage
> fairseq-train: error: argument --max-tokens: invalid Optional value: '512'

 - fairseq Version (adapted version from NMT-Adapt https://github.com/wjko2/NMT-Adapt#:~:text=Go%20to%20directory%20NMTAdapt1%2C%20and%20load%20the%20modified%20version%20of%20fairseq.%20(pip%20install%20%2D%2Deditable%20./)):

 - Python version: 3.10.4

**Comment by tianshuailu** [comment]
And also I know this question has already been asked many times, but I always get the oom error, and reducing max token size doesn't help, I already dropped from 1024 to 64 and it still oom, I think it may be not meaningful to go down below 64.

> 2022-08-12 23:42:11 | WARNING | fairseq.trainer | attempting to recover from OOM in forward/backward pass
Traceback (most recent call last):
  File "/home/user/ltian/anaconda3/bin/fairseq-train", line 33, in <module>
    sys.exit(load_entry_point('fairseq', 'console_scripts', 'fairseq-train')())
  File "/srv/scratch3/ltian/NMT-Adapt/NMTAdapt1/fairseq_cli/train.py", line 352, in cli_main
    distributed_utils.call_main(args, main)
  File "/srv/scratch3/ltian/NMT-Adapt/NMTAdapt1/fairseq/distributed_utils.py", line 254, in call_main
    nprocs=args.distributed_num_procs,
  File "/home/user/ltian/anaconda3/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 230, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/home/user/ltian/anaconda3/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 188, in start_processes
    while not context.join():
  File "/home/user/ltian/anaconda3/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 150, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException:

> -- Process 3 terminated with the following error:
> Traceback (most recent call last):
>   File "/home/user/ltian/anaconda3/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 59, in _wrap
>     fn(i, *args)
>   File "/srv/scratch3/ltian/NMT-Adapt/NMTAdapt1/fairseq/distributed_utils.py", line 238, in distributed_main
>     main(args, **kwargs)
>   File "/srv/scratch3/ltian/NMT-Adapt/NMTAdapt1/fairseq_cli/train.py", line 125, in main
>     valid_losses, should_stop = train(args, trainer, task, epoch_itr)
>   File "/home/user/ltian/anaconda3/lib/python3.7/contextlib.py", line 74, in inner
>     return func(*args, **kwds)
>   File "/srv/scratch3/ltian/NMT-Adapt/NMTAdapt1/fairseq_cli/train.py", line 208, in train
>     log_output = trainer.train_step(samples)
>   File "/home/user/ltian/anaconda3/lib/python3.7/contextlib.py", line 74, in inner
>     return func(*args, **kwds)
>   File "/srv/scratch3/ltian/NMT-Adapt/NMTAdapt1/fairseq/trainer.py", line 628, in train_step
>     raise e
>   File "/srv/scratch3/ltian/NMT-Adapt/NMTAdapt1/fairseq/trainer.py", line 591, in train_step
>     self.optimizer[0].step()
>   File "/srv/scratch3/ltian/NMT-Adapt/NMTAdapt1/fairseq/optim/fp16_optimizer.py", line 198, in step
>     self.fp32_optimizer.step(closure)
>   File "/srv/scratch3/ltian/NMT-Adapt/NMTAdapt1/fairseq/optim/fairseq_optimizer.py", line 114, in step
>     self.optimizer.step(closure)
>   File "/home/user/ltian/anaconda3/lib/python3.7/site-packages/torch/optim/optimizer.py", line 88, in wrapper
>     return func(*args, **kwargs)
>   File "/srv/scratch3/ltian/NMT-Adapt/NMTAdapt1/fairseq/optim/adam.py", line 207, in step
>     denom = exp_avg_sq.sqrt().add_(group["eps"])
> RuntimeError: CUDA out of memory. Tried to allocate 1.74 GiB (GPU 3; 11.93 GiB total capacity; 9.33 GiB already allocated; 1.64 GiB free; 9.62 GiB reserved in total by PyTorch)
>

**Comment by gmryu** [comment]
From the [#4032](https://github.com/facebookresearch/fairseq/issues/4032#issuecomment-977613382) , it looks like that `invalid Optional value` Error occurs because of your environment(like using pycharm?)
Anyway, I do not encouter.
If it troubles you, you can change that Optional[int] to int [here](https://github.com/facebookresearch/fairseq/blob/main/fairseq/dataclass/configs.py#L472)

--

About that OOM, maybe you can try `--memory-efficient-fp16`, `--optimizer adafactor`.
Also it would be nice of you to create a dummy text like `1 2 3 4 5 6 7 8 9 0`(repeated 10 times, so 100 tokens), preprocess them and train with it again. If it does not get OOM, multiple the length 2 times and do again. Once you know a valid maximum length, you can delete too long sentences from your actual data.

**Comment by tianshuailu** [comment]
> From the [#4032](https://github.com/facebookresearch/fairseq/issues/4032#issuecomment-977613382) , it looks like that `invalid Optional value` Error occurs because of your environment(like using pycharm?) Anyway, I do not encouter. If it troubles you, you can change that Optional[int] to int [here](https://github.com/facebookresearch/fairseq/blob/main/fairseq/dataclass/configs.py#L472)
> 
> --
> 
> About that OOM, maybe you can try `--memory-efficient-fp16`, `--optimizer adafactor`. Also it would be nice of you to create a dummy text like `1 2 3 4 5 6 7 8 9 0`(repeated 10 times, so 100 tokens), preprocess them and train with it again. If it does not get OOM, multiple the length 2 times and do again. Once you know a valid maximum length, you can delete too long sentences from your actual data.

Apologies for the late reply, but thank you so much, it worked and I completed the training!
