### ISSUE TITLE
Unshuffles test set during generation 

### ISSUE THREAD

**Issue by i55code** [facebookresearch/fairseq#4684]
Hi, 

How do we keep the test set sentence order during generation? Is there a flag we can pass to the generation to keep the test set sequence untouched? This is very important for my work. I would like to request the new feature. 

Thanks!

**Comment by cordercorder** [comment]
For test set, fairseq will automatically sort the sentences by length and there is no flag to keep the sentence order. Despite that, you can extract the input and output sentences by regular expression from the results produced by `fairseq-generate`  and reorder the sentences by their sample id (already in the results) to keep the order.

**Comment by i55code** [comment]
Hi @cordercorder , thank you so much! Keeping the order of sentences is important for my work, yes, sample id would work. Thanks!

**Comment by BrightXiaoHan** [comment]
These commands may help you.
```
grep ^S generate-test.txt | LC_ALL=C sort -V | cut -f2- > src.txt
grep ^T generate-test.txt | LC_ALL=C sort -V | cut -f2- > ref.txt
grep ^H generate-test.txt | LC_ALL=C sort -V | cut -f3- > hyp.txt
```
