### ISSUE TITLE
How to install fairseq without torch

### ISSUE THREAD

**Issue by moseshu** [facebookresearch/fairseq#4701]
## how to ignore the installed torch
I follow the installation 
pip install fairseq  --ignore-installed torch,It always install the latest version torch=1.12.1.
how to ignore torch ?,because I have installed torch=1.7.1
### Before asking:
1. search the issues.
2. search the docs.

#### What's your environment?

 - fairseq Version (e.g., 1.0 or main):
 - PyTorch Version (e.g., 1.7.1)
 - OS (Linux):
 - How you installed fairseq (`pip`, source):
 - pip install fairseq -ignore-installed torch
 - Build command you used (if compiling from source):
 - Python version: 1.7.1
 - CUDA/cuDNN version:10.2
 - GPU models and configuration:
 - Any other relevant information:

**Comment by SeunghyunSEO** [comment]
modify [setup.py](https://github.com/facebookresearch/fairseq/blob/main/setup.py#L209)

like below

```python
        install_requires=[
            "cffi",
            "cython",
            'dataclasses; python_version<"3.7"',
            "hydra-core>=1.0.7,<1.1",
            "omegaconf<2.1",
            'numpy<1.20.0; python_version<"3.7"',
            'numpy; python_version>="3.7"',
            "regex",
            "sacrebleu>=2.0.0",
            # "torch",
            "tqdm",
            "bitarray",
            # "torchaudio>=0.8.0",
        ],
```

**Comment by moseshu** [comment]
> 

thanks for your reply,It works
