### ISSUE TITLE
Question about the Product Kmeans in HuBERT

### ISSUE THREAD

**Issue by wangkunpeng1215** [facebookresearch/fairseq#4731]
## ❓ Questions and Help
Hi, Im trying to pretraining a new HuBERT model. I noticed the paper used Product K-means-{0,1,2}-100 to do opimization. But I dont find how and where to use it in the opensource code, which confusing me for a long time. Dose anyone know how to do it?

Thanks!!

**Comment by Labyrintbs** [comment]
Thanks for your issue, I have the same question too, did you find the answer?

**Comment by wangkunpeng1215** [comment]
> Thanks for your issue, I have the same question too, did you find the answer?

Hi, i dont know my understanding correct or not. I think the 'Product K-means-{0,1,2}' is just the concat of the zeroth,
first, and second-order derivatives in MFCC extraction.  So it just used the original MFCC to do kmeans, as those in the open source  code.

**Comment by Labyrintbs** [comment]
> > Thanks for your issue, I have the same question too, did you find the answer?
> 
> Hi, i dont know my understanding correct or not. I think the 'Product K-means-{0,1,2}' is just the concat of the zeroth, first, and second-order derivatives in MFCC extraction. So it just used the original MFCC to do kmeans, as those in the open source code.

Thank you! I understood :D
