### ISSUE TITLE
How to create an iterator that retains order of dataset?

### ISSUE THREAD

**Issue by davidstap** [facebookresearch/fairseq#4741]
Is it possible to have an iterator for a translation dataset that does not do any shuffling, i.e. retains the original order of the dataset on sentence level? I understand this will be less efficient.

In particular, I have a translation dataset consisting of 5M sentence pairs:

`dataset = task.dataset("train")`

With this dataset I initialise an iterator:

`itr = task.get_batch_iterator(dataset=dataset, max_tokens=args.max_tokens, max_sentences=args.batch_size, shuffle=False,
        max_positions=utils.resolve_max_positions(task.max_positions(), *[m.max_positions() for m in models],),
        ignore_invalid_inputs=args.skip_invalid_size_inputs_valid_test,
        required_batch_size_multiple=args.required_batch_size_multiple, seed=args.seed,
        num_shards=args.distributed_world_size, shard_id=args.distributed_rank, num_workers=args.num_workers,
        data_buffer_size=args.data_buffer_size,).next_epoch_itr(False)`

In this case, `itr` does not retain the original order. Is there any way I can make sure that the order is not changed? If this is possible, I would be extremely grateful for a code-snippet that shows how to create an order-retaining iterator from `dataset`.

I have searched the docs, comments, and have used Google, but I have not been able to find an answer. I am not very familiar with fairseq, so I could be missing something obvious. Thanks for your patience and help!

**Comment by gmryu** [comment]
(just to be sure, you are talking about sentences being sorted by their lengths, right?
If it is only about iterator, I guess you can see this https://github.com/facebookresearch/fairseq/blob/main/fairseq/data/iterators.py#L393-L406 )

I assume you are using `TranslationTask`.
So the "shuffling" is happening inside [LanguagePairDataset](https://github.com/facebookresearch/fairseq/blob/main/fairseq/data/language_pair_dataset.py#L77)
In other words, if you disable that `sort` and all `.index_select(0, sort_order)` below it,
you will get your original order.

--

If you do not wish to change the original code, so do I recommend not changing, 
You will need to make a copy of both that_task.py and that_dataset.py, alter the copy and use `--user-dir` to make fairseq recognize your new implemented task.

If you are using other tasks, then you conduct a searching in that task.py.
Find out which dataset it is using and go find it.

A tiny piece of advice. You can conduct a searching in fairseq_repository/fairseq/examples or the whole repository.
Though it won't tell you how to not shuffle data, it may tell you how to use `user-dir`, what is task? where does data be handled etc.
You are always welcomed to ask here anyway.

**Comment by davidstap** [comment]
Thanks @gmryu, this solves my issue!
