### ISSUE TITLE
MBART ckpt loading error

### ISSUE THREAD

**Issue by stdoo** [facebookresearch/fairseq#4789]
I was going to do some translation inference with MBART according to the instructions in the following page: https://github.com/facebookresearch/fairseq/blob/main/examples/mbart/README.md.

Everything went well until this command:
```
model_dir=MBART_finetuned_enro # fix if you moved the checkpoint

fairseq-generate path_2_data \
  --path $model_dir/model.pt \
  --task translation_from_pretrained_bart \
  --gen-subset test \
  -t ro_RO -s en_XX \
  --bpe 'sentencepiece' --sentencepiece-model $model_dir/sentence.bpe.model \
  --sacrebleu --remove-bpe 'sentencepiece' \
  --batch-size 32 --langs $langs > en_ro
```
The error is like:

> RuntimeError: Error(s) in loading state_dict for BARTModel:
 size mismatch for encoder.embed_tokens.weight: copying a param with shape torch.Size([250027, 1024]) from checkpoint, the shape in current model is torch.Size([250004, 1024]).
 size mismatch for decoder.embed_tokens.weight: copying a param with shape torch.Size([250027, 1024]) from checkpoint, the shape in current model is torch.Size([250004, 1024]).
 size mismatch for decoder.output_projection.weight: copying a param with shape torch.Size([250027, 1024]) from checkpoint, the shape in current model is torch.Size([250004, 1024]).

It seems that the ckpt provided cannot match the size of the BARTModel. 
How to solve this problem?

**Comment by Taoxi-stu** [comment]
I have the same error with you. Did you solve it?
