### ISSUE TITLE
AttributeError: 'dict' object has no attribute '_get_node_flag'

### ISSUE THREAD

**Issue by MLDeep16** [facebookresearch/fairseq#4834]
root/abc/venv/lib/python3.8/site-packages/omegaconf/omegaconf.py", line 670, in open_dict
prev_state = config._get_node_flag("struct")
AttributeError: 'dict' object has no attribute '_get_node_flag'

**Comment by 8904591612** [comment]
can you please tell me how did you resolve this issue
