### ISSUE TITLE
AttributeError: module 'fairseq' has no attribute 'checkpoint_utils'

### ISSUE THREAD

**Issue by tickwizard** [facebookresearch/fairseq#4874]
# Code
import torch
import fairseq

cp_path = '/path/to/wav2vec.pt'
model, cfg, task = fairseq.checkpoint_utils.load_model_ensemble_and_task([cp_path])

# Error
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'fairseq' has no attribute 'checkpoint_utils'

**Comment by lcc-404** [comment]
Hi,
I have the same problem, how did you solve it? tkx!

**Comment by liutaocode** [comment]
Current path may contain fairseq file. just remove or rename it.

**Comment by Ezreal11** [comment]
My code was at the same level of fairseq folder, move the code to the new folder and I solved it.

**Comment by drewgrant** [comment]
> Current path may contain fairseq file. just remove or rename it.
> My code was at the same level of fairseq folder, move the code to the new folder and I solved it.

Tried these and they didn't work.
