### ISSUE TITLE
multilingual finetuning NLLB translation

### ISSUE THREAD

**Issue by edchengg** [facebookresearch/fairseq#4912]
#### What is your question?
How can I finetune the NLLB multilingual translation model on multiple language pairs together?
I find the document for finetuning NLLB but it only supports one language pair. 
Anyone has experience or how should I adapt the training code to do it?
Thanks in advance! @elbayadm @vedanuj

**Comment by elbayadm** [comment]
Hi @edchengg!
For finetuning on a single pair we provided the command
```
DROP=0.1
python examples/nllb/modeling/train/train_script.py \
    cfg=nllb200_dense3.3B_finetune_on_fbseed \
    cfg/dataset=$DATA_CONFIG \
    cfg.dataset.lang_pairs="$SRC-$TGT" \
    cfg.fairseq_root=$(pwd) \
    cfg.output_dir=$OUTPUT_DIR \
    cfg.dropout=$DROP \
    cfg.warmup=10 \
    cfg.finetune_from_model=$MODEL_FOLDER/checkpoint.pt

```
If you want to finetune NLLB on multiple language pairs at the same time you can list all directions  with:
`cfg.dataset.lang_pairs="$SRC1-$TGT1,$SRC2-$TGT2"`
This assumes that the dataset config you point to with
`cfg/dataset=$DATA_CONFIG` has all those pairs in it.
Specifying `cfg.dataset.lang_pairs` in the command above overwrites the list of pairs in the data config; if you want to train/finetune on all pairs in the dataset, you can skip that line all together.

**Comment by edchengg** [comment]
Thanks a lot!
