### ISSUE TITLE
Question for XStory Cloze dataset

### ISSUE THREAD

**Issue by mkw18** [facebookresearch/fairseq#4925]
Hello! I read that XStory Cloze is translated by Story Cloze here https://github.com/facebookresearch/fairseq/blob/main/examples/xglm/model_card.md#xstorycloze. I also want to use XStory Cloze for test, and I'm trying to translate it myself, but how did you translate it, by googletrans or something else?

**Comment by todpole3** [comment]
We partnered with professional vendors to perform the translation.
