### ISSUE TITLE
'unrecognized arguments: True' when specifying --joined-dictionary

### ISSUE THREAD

**Issue by FayZ676** [facebookresearch/fairseq#4926]
## 🐛 Bug

`fairseq-preprocess: error: unrecognized arguments: True` when specifying `--joined-dictionary True`

```
fairseq-preprocess \
  --joined-dictionary True \
  --source-lang prompt --target-lang completion \
  --trainpref datasets/howard/fairseq/train \
  --validpref datasets/howard/fairseq/validation \
  --testpref datasets/howard/fairseq/test \
  --destdir data-bin/captions/
```

### Environment

 - fairseq Version (e.g., 1.0 or main): 0.12.2
 - PyTorch Version (e.g., 1.0): 1.13.1
 - OS (e.g., Linux): Ubuntu 22.04
 - How you installed fairseq (`pip`, source): source
 - Build command you used (if compiling from source): 
 - Python version: 3.8
 - CUDA/cuDNN version: 11.7
 - GPU models and configuration: 4x 3090
 - Any other relevant information:

**Comment by cordercorder** [comment]
Please try to remove `True` from `--joined-dictionary True`. Below is an example:

``` bash
fairseq-preprocess \
  --joined-dictionary \
  --source-lang prompt --target-lang completion \
  --trainpref datasets/howard/fairseq/train \
  --validpref datasets/howard/fairseq/validation \
  --testpref datasets/howard/fairseq/test \
  --destdir data-bin/captions/
```

**Comment by FayZ676** [comment]
@cordercorder thanks for quick response. This runs without any errors, but it doesn't return a joined dictionary.
<img width="1610" alt="Screen Shot 2022-12-28 at 12 23 01 PM" src="https://user-images.githubusercontent.com/94952795/209856273-8cc0d308-12e9-4c09-9c05-085d957313b4.png">

I may be missing something here since I am getting a similar `unrecognized arguments` problem in issue #4927 too.

**Comment by cordercorder** [comment]
Although two dictionaries were generated, they are identical, so there is a joint dictionary. You can use `diff` command to check this. Below is an example:
``` bash
diff dict.completion.txt dict.prompt.txt
```

**Comment by FayZ676** [comment]
Oh yeah, they're identical. Could I then just remove the duplicate and rename the other to `dict.txt`?

**Comment by cordercorder** [comment]
In the translation task, Fairseq assumes that the file names of the source dictionary and target dictionary are `dict.${source_lang}.txt` and `dict.${target_lang}.txt` respectively (please refer to the source code [here](https://github.com/facebookresearch/fairseq/blob/main/fairseq/tasks/translation.py#L308)). If you remove or rename the generated dictionary, it seems like you will need to modify the source code of Fairseq to make the code run well.

**Comment by FayZ676** [comment]
Thanks for the source code tip and explanation, that makes sense.

When I run the preprocessing script below
```
fairseq-preprocess --destdir data-bin/captions \
  --source-lang prompt --target-lang completion \
  --trainpref caption_datasets/howard/fairseq/train \
  --validpref caption_datasets/howard/fairseq/validation \
  --testpref caption_datasets/howard/fairseq/test
```
I get the two dicts shown in the previous image. Which makes sense to me.

But then when I run the training script below
```
CUDA_VISIBLE_DEVICES=0 \
fairseq-train data-bin/captions \
	--finetune-from-model en_dense_lm_125m/model.pt \
	--arch transformer_lm_gpt \
	--task language_modeling --tokens-per-sample 512 \
	--batch-size 32 \
	--optimizer adam --adam-betas '(0.9, 0.98)' --clip-norm 0.0 \
	--max-epoch 1 \
	--fp16
```

I get an error saying `FileNotFoundError: [Errno 2] No such file or directory: 'data-bin/captions/dict.txt'`. Hence I thought that I'd need to use `--joined-dictionary` in order to create the single `dict.txt` file.

Sorry for the long pre amble. This is ultimately what brought me to here lol.
