### ISSUE TITLE
 TypeError: 'NoneType' object is not iterable #1070 

### ISSUE THREAD

**Issue by kanpuriyanawab** [facebookresearch/fairseq#4996]
## 🐛 Bug

Same as [#1070](https://github.com/facebookresearch/fairseq/issues/1070) issue.

### To Reproduce

I'm facing this issue on a colab while loading roberta
 
![image](https://user-images.githubusercontent.com/51750587/221368541-77f20bdd-0747-49ec-aa14-86a49c2d5d38.png)

I tried installing fairseq itself

![Uploading image.png…]()

Still the same help

**Comment by zacharyfmarion** [comment]
Also getting this same issue on Python 3.9.13
