### ISSUE TITLE
I cant install fairseq on Windows 11.

### ISSUE THREAD

**Issue by glowingstone124** [facebookresearch/fairseq#5052]
## 🐛 Bug

my PC is running windows11 with gcc and python3.10. when i try to install fairseq, some errr occured.

### To Reproduce

      E:\vscode1\VC\Tools\MSVC\14.35.32215\include\yvals.h(17): fatal error C1083: 无法打开包括文件: “crtdbg.h”: No such file or directory
      error: command 'E:\\vscode1\\VC\\Tools\\MSVC\\14.35.32215\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for fairseq
Failed to build fairseq
ERROR: Could not build wheels for fairseq, which is required to install pyproject.toml-based projects

#### another way
I tryed to install fairseq with a .tar.gz file. failed again,
### Expected behavior
i hope i can running fairseq on windows,

**Comment by BUZZARDGTA** [comment]
You can try installing Visual Studio, and select the first "Desktop development with C++" option there:
https://visualstudio.microsoft.com/visual-cpp-build-tools/

**Comment by glowingstone124** [comment]
thanks.
