### ISSUE TITLE
MMS - is automatic language detection a thing with MMS? The mms_infer.py requires a language input to work

### ISSUE THREAD

**Issue by altryne** [facebookresearch/fairseq#5119]
#### What is your question?
How to auto-detect a language from the mms_infer.py? 

#### Code
Running

`python asr/infer/mms_infer.py --model mms1b_l1107.pt --audio output_audio.mp3` 

shows 

`the following arguments are required: --lang`

**Comment by tanmayh-fg** [comment]
i have same issue. If not automatic, is there at least a way I can give multiple language inputs, eg eng & hin.

**Comment by androstj** [comment]
We currently don't support automatic language detection given a speech. But you could use the LID to detect the language and put the predicted language code into inference script (but check if ASR support those languages or not from README table)

**Comment by altryne** [comment]
> We currently don't support automatic language detection given a speech. But you could use the LID to detect the language and put the predicted language code into inference script (but check if ASR support those languages or not from README table)

Thanks for the comment @androstj , could you elaborate on what "use the LID" means?

**Comment by androstj** [comment]
LID is Language Identification. Given a speech input, LID will predict what language is it. Check our readme section on how to run LID [MMS LID](https://github.com/facebookresearch/fairseq/tree/main/examples/mms#lid)
