### ISSUE TITLE
MMS-Where is nepali model?

### ISSUE THREAD

**Issue by xettrisomeman** [facebookresearch/fairseq#5126]
I don't find iso code for nepali language. Where is it?

**Comment by vineelpratap** [comment]
Hi, please use `npi` as the language code for MMS.

**Comment by xettrisomeman** [comment]
Not working.

This is iso codes text file.
![image](https://github.com/facebookresearch/fairseq/assets/44607279/0ea041b6-f0d4-436a-9303-7e80415ad8f9)

Using the iso code(npi).
![image](https://github.com/facebookresearch/fairseq/assets/44607279/4b51abce-b7f2-402d-870d-8dbd30a60a31)
