### ISSUE TITLE
MMS: Whisper-like translation to English possible?

### ISSUE THREAD

**Issue by NotNANtoN** [facebookresearch/fairseq#5129]
#### What is your question?

The Whisper model has a mode to detect a language automatically, and then translate from that language to English while doing speech-to-text. I'm wondering if that is also possible with the MMS models. 

It would be completely fine for me if there are models for each part, but one key point that I did not see is detecting the language. The other problem would be the translation from that language to English - there are quite some open source models to do so, but it would be super nice if the STT model could do it internally already.

**Comment by vineelpratap** [comment]
Hi, we also release Language Identification models - https://github.com/facebookresearch/fairseq/blob/main/examples/mms/README.md#lid. 

> translation from that language to English  

We do not support translation in MMS at the moment.

**Comment by Jackylee2032** [comment]
when it comes to unwritten languages as hokkien，how can  mms transcript it?any demo?
