### ISSUE TITLE
MMS: where is the Letter dictionary?

### ISSUE THREAD

**Issue by zhhao1** [facebookresearch/fairseq#5131]
During inference, a letter dictionary is needed. Where can is find it?

**Comment by androstj** [comment]
The dictionary has been serialized into model['task_state'] and can be used without specify-ing target_dictionary explicitly. Do you get any error message?

**Comment by zhhao1** [comment]
> The dictionary has been serialized into model['task_state'] and can be used without specify-ing target_dictionary explicitly. Do you get any error message?

Thanks for your answer. I want to convert it to the model that Huggingface can use, so I'm looking for a dictionary . Run directly on fairseq with no errors. Great work.

**Comment by androstj** [comment]
@zhhao1 We added dictionary folders in the [readme](https://github.com/facebookresearch/fairseq/tree/main/examples/mms)
Compared to previous fairseq ASR, our current model has multiple dictionaries (1 dict for 1 iso-script). So please follow the instructions to download the dictionary based on the languages you want.

**Comment by zhhao1** [comment]
> @zhhao1 We added dictionary folders in the [readme](https://github.com/facebookresearch/fairseq/tree/main/examples/mms) Compared to previous fairseq ASR, our current model has multiple dictionaries (1 dict for 1 iso-script). So please follow the instructions to download the dictionary based on the languages you want.

Thanks for you kind reply. Not all heros wear capes.
