### ISSUE TITLE
MMS: Catalan "L·L" inferred sound wrongly

### ISSUE THREAD

**Issue by jmontane** [facebookresearch/fairseq#5134]
Context: Middle dot U+00B7 is used in Catalan language as inner word punctuation/diacritical mark just to difference pronunciation of "L·L" and "LL". "L·L" sounds a long el (cel·la, goril·la, excel·lent, paral·lel), and "LL" sounds like /ʎ/ (cella, lluna, allà). 

TTS from MMS ignores Catalan middle dot. I've inferred some audios from texts in Catalan language, and there is an issue around [Catalan L·L](https://en.wikipedia.org/wiki/Interpunct#Catalan). TTS from MMS treats L·L like LL. It's wrong, 

L·L must sound like a single el or, in a very formal context, like a long el. Example "goril·la" sounds like /ɡuˈɾi.ɫə/ or /ɡuˈɾiɫ.ɫə/ formal, but generated audios with MMS sound like  /ɡuˈɾiʎə/ (it's wrong)

I've tested with several words containing L·L and this issue always arises: "L·L" always sounds wrongly like /ʎ/.

**Comment by vineelpratap** [comment]
It looks like middle dot was included as a punctuation in MMS - https://github.com/facebookresearch/fairseq/blob/main/examples/mms/data_prep/punctuations.lst#L94

So, we are indeed ignoring it in MMS. We will try to fix it in our next release.
