### ISSUE TITLE
lid dictionary 1024 is not downloadable - permissions? 

### ISSUE THREAD

**Issue by codeisnotcode** [facebookresearch/fairseq#5135]
## 🐛 Bug

At page https://github.com/facebookresearch/fairseq/tree/main/examples/mms
there is a table under heading LID that has a matrix of downloadable items.
The entry for row 1024, column Dictionary is not downloadable. 

### To Reproduce

Go to page https://github.com/facebookresearch/fairseq/tree/main/examples/mms
Right-click it, select 'Save As' from the pop-up menu, and choose a filename.
The download fails.

If you left-click on it (rather than right-click, 'save as'), it returns the following:
<Error>
<script/>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>KAXWZ1HRVXJ5GFWY</RequestId>
<HostId>SVDZwLefcs6cPXqxIOYB4aA7y+CrL2lybWtOveXVd3tCjewZw77YzUKvwEwlR0uQwvpyNixpzv0=</HostId>
</Error>

#### Code sample

see above

### Expected behavior

I expected to be able to download the file, as works with the other entries in column Dictionary.

### Environment

Chrome Version 113.0.5672.93 (Official Build) (64-bit)
Windows 10 22H2 v 19045.2965

**Comment by vineelpratap** [comment]
Fixed now!
