### ISSUE TITLE
text after filtering OOV is empty output 

### ISSUE THREAD

**Issue by lisea2017** [facebookresearch/fairseq#5142]
Japanese TTS
downloaded the model with - wget https://dl.fbaipublicfiles.com/mms/tts/jvn.tar.gz

after running infer.py, there is no text after the line - text after filtering OOV:

What's the problem？

**Comment by chevalierNoir** [comment]
@lisea2017 `jvn` is "Javanese Surinamese", not Japanese.

**Comment by lisea2017** [comment]
Sorry, if I want to try Japanese, which one should I use?

**Comment by w-ww** [comment]
There is no TTS model supporting Japanese. You can check the list.
https://dl.fbaipublicfiles.com/mms/misc/language_coverage_mms.html

**Comment by lisea2017** [comment]
If I want to support Japanese, is there a plan and what should I do?

**Comment by serkandyck** [comment]
> There is no TTS model supporting Japanese. You can check the list. https://dl.fbaipublicfiles.com/mms/misc/language_coverage_mms.html

same on turkish oov filtering letter like "Ç", "İ", "Ö"
![image](https://github.com/facebookresearch/fairseq/assets/12444059/f914edcd-39ca-4283-a137-fa087d8eb473)

**Comment by chevalierNoir** [comment]
> > There is no TTS model supporting Japanese. You can check the list. https://dl.fbaipublicfiles.com/mms/misc/language_coverage_mms.html
> 
> same on turkish oov filtering letter like "Ç", "İ", "Ö" ![image](https://user-images.githubusercontent.com/12444059/240640022-f914edcd-39ca-4283-a137-fa087d8eb473.png)

See the thread [here](https://github.com/facebookresearch/fairseq/issues/5125#issuecomment-1561477259)

**Comment by chevalierNoir** [comment]
> If I want to support Japanese, is there a plan and what should I do?

@lisea2017 Japanese TTS is not supported due to some technical issues. But you could train a TTS model for Japanese using the VITS code with some public Japanese speech datasets.

**Comment by lisea2017** [comment]
ok.thanks
