### ISSUE TITLE
Why there is no Chinese in MMS?

### ISSUE THREAD

**Issue by lucasjinreal** [facebookresearch/fairseq#5145]
zh-cmn

![image](https://github.com/facebookresearch/fairseq/assets/21303438/968faaa3-75a0-400b-a786-d912453fd077)

does cantoness not included?

**Comment by chevalierNoir** [comment]
@lucasjinreal For Chinese Mandarin(cmn) we support ASR but not TTS. Check [this table](https://dl.fbaipublicfiles.com/mms/misc/language_coverage_mms.html)

**Comment by lucasjinreal** [comment]
oh，so pity
