### ISSUE TITLE
How can we use Massively Multilingual Speech (MMS) commercially?

### ISSUE THREAD

**Issue by troublesprouter** [facebookresearch/fairseq#5150]
Can MMS be used commercially? How?

**Comment by vineelpratap** [comment]
MMS is released under CC-BY-NC 4.0 license. It cannot be used for commercial purposes.

**Comment by TechInterMezzo** [comment]
@vineelpratap 
> MMS is released under CC-BY-NC 4.0 license. It cannot be used for commercial purposes.

Is it possible to create a synthetic dataset with MMS output and allow commercial use for that dataset?
