### ISSUE TITLE
MMS tts discriminator files release

### ISSUE THREAD

**Issue by sankar-mukherjee** [facebookresearch/fairseq#5156]
Thank you meta for the opensourcing Massively Multilingual Speech project. I have one question.

For tts will there be a release of discriminator files D_*.pth for the Massively Multilingual Speech project?

https://github.com/facebookresearch/fairseq/tree/main/examples/mms

**Comment by chevalierNoir** [comment]
@sankar-mukherjee we are working on it right now and will release it soon.

**Comment by chevalierNoir** [comment]
The discriminator checkpoints are available now, check the instructions [here](https://github.com/facebookresearch/fairseq/tree/main/examples/mms#tts).
