### ISSUE TITLE
MMS - Request for Colab notebook for TTS inference 

### ISSUE THREAD

**Issue by wyuzh** [facebookresearch/fairseq#5161]
Thank you for create the Colab notebook for ASR and LID inference, may I request for the Colab notebook for TTS inference?

**Comment by chevalierNoir** [comment]
@zhangwengyu999 We are working on it now and will put a TTS notebook soon.

**Comment by chevalierNoir** [comment]
@zhangwengyu999 The TTS [notebook](https://github.com/facebookresearch/fairseq/tree/main/examples/mms#tts-1) is available now.
