### ISSUE TITLE
How to convert mms model to hf model?

### ISSUE THREAD

**Issue by glogskun12303** [facebookresearch/fairseq#5163]
#### I tried using the conversion script in Huggingface Transformers ```python convert_wav2vec2_original_pytorch_checkpoint_to_pytorch.py  --pytorch_dump_folder_path=/hy-tmp/asr-hf --checkpoint_path=/hy-tmp/asr/model.pt --dict_path=/hy-tmp/asr/uig-script_arabic.txt ``` 
Got the following error:
ValueError: Shape of hf is torch. Size ([768]), but should be torch. Size ([1280]) for w2v_ Encoder.w2v_ model.mask_ emb
Or is there a method that can use fairseq pipeline to infer ASR, TTS, LID model Pipline like 
```pipline = TransformerModel.from_pretrained(model_name_or_path)
pipline.translate('Hello world', beam=5)```
 - fairseq Version 0.12.2
 - PyTorch Version 2.0.1)
 - OS (e.g., Linux):
 - How you installed fairseq (source):
 - Build command you used (pip install -e ./):
 - Python version:3.8
 - CUDA/cuDNN version:11.3
 - GPU models and configuration:V100-32G
 - Any other relevant information:
 -Transformers  Version: 4.30.0.dev0

**Comment by vineelpratap** [comment]
Hi, MMS uses Transformer layer with an additional adapter module which is not used on original wav2vec2.0. 
See - https://github.com/facebookresearch/fairseq/blob/main/fairseq/models/wav2vec/wav2vec2.py#L978, https://github.com/facebookresearch/fairseq/blob/main/examples/speech_recognition/new/infer.py#L108 

You would have to make appropriate changes in your conversion script.
