### ISSUE TITLE
About the way to simplify MMS inference

### ISSUE THREAD

**Issue by LYPinASR** [facebookresearch/fairseq#5164]
## 🚀 Feature Request

At present, models such as W2V2 can be called directly with the following command: 
model_path = "/ path/to/your/wav2vec/model"
model = Wav2VecModel.from_pretrained(model_path, checkpoint_file='checkpoint_best.pt')
I also want to call MMS in the same way and do speech recognition directly.

### Motivation
The MMS home page provides an inference command, but that's through indirect calls to examples/speech_recognition/new/infer. I'd like to simplify this step. For example, after calling the model, you can type in a speech and then get the corresponding text directly, just like a demo.

Look forward to it.

**Comment by vineelpratap** [comment]
There is some work being done by the HF team in https://github.com/huggingface/transformers/pull/23813/.
