### ISSUE TITLE
MMS transcribe audio.wav is error

### ISSUE THREAD

**Issue by moseshu** [facebookresearch/fairseq#5180]
## 👉 python examples/mms/asr/infer/mms_infer.py --model "/path/to/asr/model" --lang lang_code \
  --audio "/path/to/audio_1.wav" "/path/to/audio_2.wav" "/path/to/audio_3.wav" 
It throws the error is  ```RuntimeError: Error(s) in loading state_dict for Wav2VecCtc:
        Unexpected key(s) in state_dict: "w2v_encoder.w2v_model.encoder.layers.0.adapter_layer.W_a", 
"w2v_encoder.w2v_model.encoder.layers.0.adapter_layer.W_b", "w2v_encoder.w2v_model.encoder.layers.0.adapter_layer.b_a", 
"w2v_encoder.w2v_model.encoder.layers.0.adapter_layer.b_b", "w2v_encoder.w2v_model.encoder.layers.0.adapter_layer.ln_W", 
"w2v_encoder.w2v_model.encoder.layers.0.adapter_layer.ln_b", .... ```

the model is mms1b_all.pt.
python version :python3.9
cuda: 11.7
torch:1.13.1
how to solve this error.

**Comment by androstj** [comment]
Have you pull to the latest fairseq-py master branch?

**Comment by moseshu** [comment]
> Have you pull to the latest fairseq-py master branch?
fairseq version is 0.12.2?is it OK?

**Comment by moseshu** [comment]
> Have you pull to the latest fairseq-py master branch?
I change the torch version to 2.0.1.  got the same errors .but it run successfully on colab? so what is wrong with my env?
fairseq-0.12.2
pytho-3.9.10
torch-2.0.1
cuda11.7
ubuntu 20.4
model is mms1b_all.pt

**Comment by patrickvonplaten** [comment]
BTW, it should now be very simple to use MMS with `transformers`:

See:
- https://huggingface.co/docs/transformers/main/en/model_doc/mms
- https://github.com/huggingface/transformers/pull/23813
- https://huggingface.co/facebook/mms-1b-all

**Comment by moseshu** [comment]
> BTW, it should now be very simple to use MMS with `transformers`:
> 
> See:
> 
> * https://huggingface.co/docs/transformers/main/en/model_doc/mms
> * [[MMS] Scaling Speech Technology to 1,000+ Languages | Add attention adapter to Wav2Vec2 huggingface/transformers#23813](https://github.com/huggingface/transformers/pull/23813)
> * https://huggingface.co/facebook/mms-1b-all

Thansk, it's solved by following your guide
