### ISSUE TITLE
[MMS ASR] The doc for calc WER/CER can be unclear

### ISSUE THREAD

**Issue by CopyNinja1999** [facebookresearch/fairseq#5205]
As the doc says:

> $ ls /path/to/manifest
> dev.tsv
> dev.wrd
> dev.ltr
> dev.uid
> 
> \# dev.tsv each line contains <audio>  <number_of_sample>
> $ cat dev.tsv
> /
> /path/to/audio_1  180000
> /path/to/audio_2  200000
> 
> $ cat dev.ltr
> t h i s | i s | o n e |
> t h i s | i s | t w o |
> 
> $ cat dev.wrd
> this is one
> this is two
> 
> $ cat dev.uid
> audio_1
> audio_2

There are several points that can lead to misunderstanding. Is the  /path/to/audio_1 indicates a directory or a wav file? What does the number of samples mean?

**Comment by androstj** [comment]
I added new readme and scripts on how to get the sample for waveform. Please check examples/mms/misc/get_sample_size.py
