### ISSUE TITLE
MMS - Forced Alignment: log_probs shapes problem

### ISSUE THREAD

**Issue by codemurt** [facebookresearch/fairseq#5242]
## 🐛 Bug

I want to make forced alignment an audio file with its text transcription, but I encounter this issue when I run this command: `python align_and_segment.py --audio_filepath audio.wav --text_filepath text.txt --lang udm --outdir output --uroman uroman/bin`.

I got this error: `RuntimeError: log_probs must be 3-D (batch_size, input length, num classes)`.

It seems to have happened after this [commit](https://github.com/pytorch/audio/commit/cc164478f3031cc414f4938c3ec35e113063fded).

Thanks!

**Comment by skanda1005** [comment]
I am facing the same issue. Have you found any solution to this issue?

Thanks!

**Comment by codemurt** [comment]
@skanda1005, using `pip install --pre torchaudio==2.1.0.dev20230627+cu118 --index-url https://download.pytorch.org/whl/nightly/cu118` instead of `pip install --pre torchaudio --index-url https://download.pytorch.org/whl/nightly/cu118` fixed the issue for me. 

I found this solution from [here](https://github.com/facebookresearch/fairseq/issues/5248).

**Comment by skanda1005** [comment]
Thanks a lot! Worked for me as well!

**Comment by qunash** [comment]
> @skanda1005, using `pip install --pre torchaudio==2.1.0.dev20230627+cu118 --index-url https://download.pytorch.org/whl/nightly/cu118` instead of `pip install --pre torchaudio --index-url https://download.pytorch.org/whl/nightly/cu118` fixed the issue for me.
> 
> I found this solution from [here](https://github.com/facebookresearch/fairseq/issues/5248).

I installed this version and now `torchaudio.load` does not work. None of the nightly builds seem to work, it's either this `log_probs must be 3-D` error or `torchaudio.load` not working. Sigh.

**Comment by pbrusco** [comment]
Same here. torchaudio==2.1.0.dev20230627+cu118 was available last week. Any chance we can get that version from any other source?

Thanks!

**Comment by vineelpratap** [comment]
Fixed in https://github.com/facebookresearch/fairseq/pull/5317.
