### ISSUE TITLE
Question about HuBert base model pretraining

### ISSUE THREAD

**Issue by asr-pub** [facebookresearch/fairseq#5246]
#### What is your question?

![Snipaste_2023-07-09_23-57-37](https://github.com/facebookresearch/fairseq/assets/22003430/2fe020dc-b9fc-4d3d-aa5a-fa29b39fb149)

**Comment by asr-pub** [comment]
![image](https://github.com/facebookresearch/fairseq/assets/22003430/9b0bea2d-e268-4b69-a3ba-b5db2842109f)

**Comment by GUOhm230** [comment]
Have you solved the problem?

**Comment by asr-pub** [comment]
> Have you solved the problem?

Yes，the answer is on the picture.
