### ISSUE TITLE
mms data preparation doesn't work with latest nightly torchaudio build

### ISSUE THREAD

**Issue by GBurg** [facebookresearch/fairseq#5248]
I used this tutorial: https://github.com/facebookresearch/fairseq/tree/main/examples/mms/data_prep

To setup a forced alignment system with mms, however, when I reinstalled my conda environment today, (10th of July 2023), it didn't run anymore, as the torchaudio nightly build is incompatible with the code in the example. The nightly build requires an extra dimension for the emissions variable (probably a batch dimension). 
Reverting the code to 27th of Juny 2023 (using `pip install --pre torchaudio==2.1.0.dev20230627+cu118 --index-url https://download.pytorch.org/whl/nightly/cu118` instead of `pip install --pre torchaudio --index-url https://download.pytorch.org/whl/nightly/cu118` ) fixed the issue for me. But would be nice if the tutorial and code could be updated to work with the new batch in the nightly build.

```
def get_alignments(
    audio_waveform,
    tokens,
    model,
    dictionary,
    use_star,
    sample_rate
):
    # Generate emissions
    # emissions, stride = generate_emissions(model, audio_file)
    emissions, stride =  generate_emissions_waveform(model, audio_waveform, sample_rate)
    T, N = emissions.size()
    if use_star:
        emissions = torch.cat([emissions, torch.zeros(T, 1).to(DEVICE)], dim=1)

    # Force Alignment
    if tokens:
        token_indices = [dictionary[c] for c in " ".join(tokens).split(" ") if c in dictionary]
    else:
        print(f"Empty transcript!!!!! for audio file {audio_waveform}")
        token_indices = []

    blank = dictionary["<blank>"]
    
    targets = torch.tensor(token_indices, dtype=torch.int32).to(DEVICE)
    input_lengths = torch.tensor(emissions.shape[0])
    target_lengths = torch.tensor(targets.shape[0])

    path, scores = F.forced_align(
        emissions, targets, input_lengths, target_lengths, blank=blank
    )
    path = path.to("cpu").tolist()
    segments, scores_segments = merge_repeats_scores(path, scores, {v: k for k, v in dictionary.items()})
    return segments, stride, scores_segments
    ```

**Comment by GBurg** [comment]
Great you managed to get it to run. I run it on a Windows desktop with 12GB VRAM. I noticed it uses about 5-7 GB of VRAM.

**Comment by vineelpratap** [comment]
We fixed this issue now. Thanks to @yaya-sy for sending the PR.

**Comment by yaya-sy** [comment]
How this issue was fixed ? I can't see any merged of the PR.

**Comment by vineelpratap** [comment]
Ah! looks like the change was commited to your local branch. 

Fixed in https://github.com/facebookresearch/fairseq/pull/5317 now.
