### ISSUE TITLE
Question reg. fairseq mms/data_prep/align_and_segment.py

### ISSUE THREAD

**Issue by spanta28** [facebookresearch/fairseq#5302]
I am testing the mms/data_prep/align_and_segment.py code with some datasets and wanted to know some info. In the paper, its mentioned that "After manual inspection of sample quality and their corresponding score for several languages, we select −0.2 as the threshold and choose samples with scores greater than this threshold." 
So does the mms/data_prep/align_and_segment.py code do the above mentioned qc, in essence I want to know if the outputs from this code were given directly as inputs to the tts model as training data? If not could you point me to the code that does the qc . I am just testing with various inputs to see if TTS model can be improved for a specific language.

Thanks

**Comment by vineelpratap** [comment]
The "align_and_segment.py" doesn't do the filtering mentioned above. 
The reason we filter is because we were using a specific dataset based on religious texts which we found to be noisy. It won't be needed for cases where audio and the corresponding text match.

**Comment by spanta28** [comment]
Got it. Thanks
