### ISSUE TITLE
measure teacher quality

### ISSUE THREAD

**Issue by ShovalMessica** [facebookresearch/fairseq#5307]
Hi!

I'm having my own quantizer and I'm trying to use the code in **measure_teacher_quality.py** to calculate phone purity, cluster purity and PNMI.
I'm not sure what exactly are the next args in the main function:
`tsv_dir, lab_dir, lab_name, ref_lab_dir, ref_lab_name, lab_sets, phn_dir.`
In what 'dir' should be the quantize representations? The tsv_dir is of the raw audio?

In addition, how can I extract the reference phones to a file as you did?:
`parser.add_argument(
        "--phn_dir",
        default="/checkpoint/wnhsu/data/librispeech/960h/fa/raw_phn/phone_frame_align_v1",
    )`

I would appreciate your help! :)

**Comment by Abdullah955** [comment]
have you solved it ? i'm facing the same issue here. not sure how to setup the measure_teacher_quality.py file

**Comment by xxchauncey** [comment]
you may find answer in ESPNet repo where there is a same script, https://github.com/espnet/espnet/blob/master/egs2/TEMPLATE/asr1/scripts/feats/perform_kmeans.sh#L290

**Comment by HuangZikang-TJU** [comment]
have you solved it? how can i extract the reference phones to a file. Thank you!
