### ISSUE TITLE
Tokenizer token_type_ids all zeros

### ISSUE THREAD

**Issue by sa5r** [facebookresearch/fairseq#5383]
## 🐛 Bug

When using `RobertaTokenizer` in PyTorch for input of two sentences, the `token_type_ids` returns tensor with zeros, whereas it supposed to have some 1 values to distinguish between the two sentences in the encoded ids.

### To Reproduce
```
from transformers import RobertaTokenizer

tokenizer = RobertaTokenizer.from_pretrained("roberta-large")

sentence_a = "this is a sentence"
sentence_b = "this is another sentence"

encoding = tokenizer(sentence_a, sentence_b, padding=True, truncation=True, return_token_type_ids=True)
print(encoding)
```

```
{'input_ids': [0, 9226, 16, 10, 3645, 2, 2, 9226, 16, 277, 3645, 2], 'token_type_ids': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 'attention_mask': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]}
```

**Comment by Vialt6** [comment]
I think this occurs because RoBERTadoesn't have token_type_ids. The distinction between 2 sentences is encoded differently.

**Comment by sa5r** [comment]
In fact Roberta model accepts token_type_ids

**Comment by sa5r** [comment]
Just found that RoBERTa doesn’t have token_type_ids, you don’t need to indicate which token belongs to which segment.
