### ISSUE TITLE
MMS 下载预训练模型MMS-1B:L1107，想测试一下安多藏语

### ISSUE THREAD

**Issue by didi222-lqq** [facebookresearch/fairseq#5451]
### To Reproduce

Steps to reproduce the behavior (**always include the command you ran**):

1. Run cmd 'python examples/mms/asr/infer/mms_infer.py --model "/models_new/mms1b_l1107.pt" --lang "adx" --audio "/audio_samples/145-06-c.wav"'
2. See error "soundfile.LibsndfileError: Error opening '/audio_samples/145-06-c.wav': System error."

![微信图片_20240305211018](https://github.com/facebookresearch/fairseq/assets/84363031/d8b02a53-de7d-4367-9dc7-67ead08f470d)

**Comment by jackylee1** [comment]
do you solve the problem,i have same error
