### ISSUE TITLE
Can't find fairseq/version.txt during pip installation

### ISSUE THREAD

**Issue by GryffindorLi** [facebookresearch/fairseq#5556]
#### What is your question?

I am installing [Amphion](https://github.com/open-mmlab/Amphion), which depends on fairseq (see [here](https://github.com/open-mmlab/Amphion/blob/main/env.sh#L23)). However, I got the following error when installing `fairseq` with pip.

![Screenshot from 2024-10-18 16-10-11](https://github.com/user-attachments/assets/4dfa1def-b70d-4a60-8674-e72222e706cd)

Can someone help me with this issue?

#### Code

```pip install fairseq```

#### What have you tried?

I've tried to install [Amphion](https://github.com/open-mmlab/Amphion) with a higher version of Python. I also tried to install it without the version specification in the [env.sh](https://github.com/open-mmlab/Amphion/blob/main/env.sh). Both give me the same error.

#### What's your environment?

 - fairseq Version: 0.12.2
 - PyTorch Version: 2.0.1
 - OS: Ubuntu 22.04 LTS
 - How you installed fairseq: pip
 - Python version: 3.9.15 according to Amphion
 - CUDA/cuDNN version: CUDA 12.6

**Comment by jpgallegoar** [comment]
Could you fix this?

**Comment by aspil** [comment]
Downgrade pip with `pip install --upgrade pip==24.0` and it should work
